/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Button } from './button';
// May contain unused imports in some cases
// @ts-ignore
import { ButtonEmoji } from './button-emoji';
// May contain unused imports in some cases
// @ts-ignore
import { ChannelSelect } from './channel-select';
// May contain unused imports in some cases
// @ts-ignore
import { InputText } from './input-text';
// May contain unused imports in some cases
// @ts-ignore
import { MentionableSelect } from './mentionable-select';
// May contain unused imports in some cases
// @ts-ignore
import { MessageComponentTypes } from './message-component-types';
// May contain unused imports in some cases
// @ts-ignore
import { RoleSelect } from './role-select';
// May contain unused imports in some cases
// @ts-ignore
import { StringSelect } from './string-select';
// May contain unused imports in some cases
// @ts-ignore
import { TextStyleTypes } from './text-style-types';
// May contain unused imports in some cases
// @ts-ignore
import { UserSelect } from './user-select';

/**
 * @type ActionRowComponentsInner
 * @export
 */
export type ActionRowComponentsInner = Button | ChannelSelect | InputText | MentionableSelect | RoleSelect | StringSelect | UserSelect;


