/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ActionRowComponentsInner } from "./action-row-components-inner";
// May contain unused imports in some cases
// @ts-ignore
import { MessageComponentTypes } from "./message-component-types";

/**
 *
 * @export
 * @interface ActionRow
 */
export interface ActionRow {
    /**
     *
     * @type {MessageComponentTypes}
     * @memberof ActionRow
     */
    type: MessageComponentTypes;
    /**
     *
     * @type {Array<ActionRowComponentsInner>}
     * @memberof ActionRow
     */
    components: Array<ActionRowComponentsInner>;
}
