/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { MetadataItemTypes } from "./metadata-item-types";

/**
 *
 * @export
 * @interface ApplicationRoleConnectionsMetadataItemResponse
 */
export interface ApplicationRoleConnectionsMetadataItemResponse {
    /**
     *
     * @type {MetadataItemTypes}
     * @memberof ApplicationRoleConnectionsMetadataItemResponse
     */
    type: MetadataItemTypes;
    /**
     *
     * @type {string}
     * @memberof ApplicationRoleConnectionsMetadataItemResponse
     */
    key: string;
    /**
     *
     * @type {string}
     * @memberof ApplicationRoleConnectionsMetadataItemResponse
     */
    name: string;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof ApplicationRoleConnectionsMetadataItemResponse
     */
    name_localizations?: { [key: string]: string };
    /**
     *
     * @type {string}
     * @memberof ApplicationRoleConnectionsMetadataItemResponse
     */
    description: string;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof ApplicationRoleConnectionsMetadataItemResponse
     */
    description_localizations?: { [key: string]: string };
}
