/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandOptionIntegerChoice } from "./application-command-option-integer-choice";
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandOptionType } from "./application-command-option-type";

/**
 *
 * @export
 * @interface ApplicationCommandIntegerOption
 */
export interface ApplicationCommandIntegerOption {
    /**
     *
     * @type {ApplicationCommandOptionType}
     * @memberof ApplicationCommandIntegerOption
     */
    type: ApplicationCommandOptionType | null;
    /**
     *
     * @type {string}
     * @memberof ApplicationCommandIntegerOption
     */
    name: string;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof ApplicationCommandIntegerOption
     */
    name_localizations?: { [key: string]: string };
    /**
     *
     * @type {string}
     * @memberof ApplicationCommandIntegerOption
     */
    description: string;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof ApplicationCommandIntegerOption
     */
    description_localizations?: { [key: string]: string };
    /**
     *
     * @type {boolean}
     * @memberof ApplicationCommandIntegerOption
     */
    required?: boolean | null;
    /**
     *
     * @type {boolean}
     * @memberof ApplicationCommandIntegerOption
     */
    autocomplete?: boolean | null;
    /**
     *
     * @type {Array<ApplicationCommandOptionIntegerChoice>}
     * @memberof ApplicationCommandIntegerOption
     */
    choices?: Array<ApplicationCommandOptionIntegerChoice>;
    /**
     *
     * @type {any}
     * @memberof ApplicationCommandIntegerOption
     */
    min_value?: any;
    /**
     *
     * @type {any}
     * @memberof ApplicationCommandIntegerOption
     */
    max_value?: any;
}
