/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { InteractionApplicationCommandAutocompleteCallbackIntegerData } from "./interaction-application-command-autocomplete-callback-integer-data";
// May contain unused imports in some cases
// @ts-ignore
import { InteractionApplicationCommandAutocompleteCallbackNumberData } from "./interaction-application-command-autocomplete-callback-number-data";
// May contain unused imports in some cases
// @ts-ignore
import { InteractionApplicationCommandAutocompleteCallbackStringData } from "./interaction-application-command-autocomplete-callback-string-data";

/**
 *
 * @export
 * @interface ApplicationCommandAutocompleteCallbackRequestData
 */
export interface ApplicationCommandAutocompleteCallbackRequestData {
    /**
     *
     * @type {any}
     * @memberof ApplicationCommandAutocompleteCallbackRequestData
     */
    choices?: any;
}
