/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandCreateRequestOptionsInner } from "./application-command-create-request-options-inner";

/**
 *
 * @export
 * @interface ApplicationCommandPatchRequestPartial
 */
export interface ApplicationCommandPatchRequestPartial {
  /**
   *
   * @type {string}
   * @memberof ApplicationCommandPatchRequestPartial
   */
  name?: string;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof ApplicationCommandPatchRequestPartial
   */
  name_localizations?: { [key: string]: string };
  /**
   *
   * @type {string}
   * @memberof ApplicationCommandPatchRequestPartial
   */
  description?: string | null;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof ApplicationCommandPatchRequestPartial
   */
  description_localizations?: { [key: string]: string };
  /**
   *
   * @type {Array<ApplicationCommandCreateRequestOptionsInner>}
   * @memberof ApplicationCommandPatchRequestPartial
   */
  options?: Array<ApplicationCommandCreateRequestOptionsInner>;
  /**
   *
   * @type {number}
   * @memberof ApplicationCommandPatchRequestPartial
   */
  default_member_permissions?: number | null;
  /**
   *
   * @type {boolean}
   * @memberof ApplicationCommandPatchRequestPartial
   */
  dm_permission?: boolean | null;
}
