/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandPermissionType } from "./application-command-permission-type";

/**
 *
 * @export
 * @interface ApplicationCommandPermission
 */
export interface ApplicationCommandPermission {
    /**
     *
     * @type {any}
     * @memberof ApplicationCommandPermission
     */
    id: any;
    /**
     *
     * @type {ApplicationCommandPermissionType}
     * @memberof ApplicationCommandPermission
     */
    type: ApplicationCommandPermissionType | null;
    /**
     *
     * @type {boolean}
     * @memberof ApplicationCommandPermission
     */
    permission: boolean;
}
