/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandOptionType } from "./application-command-option-type";

/**
 *
 * @export
 * @interface ApplicationCommandBooleanOptionResponse
 */
export interface ApplicationCommandBooleanOptionResponse {
  /**
   *
   * @type {ApplicationCommandOptionType}
   * @memberof ApplicationCommandBooleanOptionResponse
   */
  type: ApplicationCommandOptionType | null;
  /**
   *
   * @type {string}
   * @memberof ApplicationCommandBooleanOptionResponse
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof ApplicationCommandBooleanOptionResponse
   */
  name_localized?: string | null;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof ApplicationCommandBooleanOptionResponse
   */
  name_localizations?: { [key: string]: string };
  /**
   *
   * @type {string}
   * @memberof ApplicationCommandBooleanOptionResponse
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof ApplicationCommandBooleanOptionResponse
   */
  description_localized?: string | null;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof ApplicationCommandBooleanOptionResponse
   */
  description_localizations?: { [key: string]: string };
  /**
   *
   * @type {boolean}
   * @memberof ApplicationCommandBooleanOptionResponse
   */
  required?: boolean | null;
}
