/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandAttachmentOptionResponse } from "./application-command-attachment-option-response";
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandBooleanOptionResponse } from "./application-command-boolean-option-response";
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandChannelOptionResponse } from "./application-command-channel-option-response";
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandIntegerOptionResponse } from "./application-command-integer-option-response";
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandMentionableOptionResponse } from "./application-command-mentionable-option-response";
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandNumberOptionResponse } from "./application-command-number-option-response";
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandOptionType } from "./application-command-option-type";
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandRoleOptionResponse } from "./application-command-role-option-response";
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandStringOptionResponse } from "./application-command-string-option-response";
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandSubcommandGroupOptionResponse } from "./application-command-subcommand-group-option-response";
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandSubcommandOptionResponse } from "./application-command-subcommand-option-response";
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandUserOptionResponse } from "./application-command-user-option-response";

/**
 * @type ApplicationCommandResponseOptionsInner
 * @export
 */
export type ApplicationCommandResponseOptionsInner =
    | ApplicationCommandAttachmentOptionResponse
    | ApplicationCommandBooleanOptionResponse
    | ApplicationCommandChannelOptionResponse
    | ApplicationCommandIntegerOptionResponse
    | ApplicationCommandMentionableOptionResponse
    | ApplicationCommandNumberOptionResponse
    | ApplicationCommandRoleOptionResponse
    | ApplicationCommandStringOptionResponse
    | ApplicationCommandSubcommandGroupOptionResponse
    | ApplicationCommandSubcommandOptionResponse
    | ApplicationCommandUserOptionResponse;
