/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandCreateRequestOptionsInner } from "./application-command-create-request-options-inner";
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandType } from "./application-command-type";

/**
 *
 * @export
 * @interface ApplicationCommandCreateRequest
 */
export interface ApplicationCommandCreateRequest {
    /**
     *
     * @type {string}
     * @memberof ApplicationCommandCreateRequest
     */
    name: string;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof ApplicationCommandCreateRequest
     */
    name_localizations?: { [key: string]: string };
    /**
     *
     * @type {string}
     * @memberof ApplicationCommandCreateRequest
     */
    description?: string | null;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof ApplicationCommandCreateRequest
     */
    description_localizations?: { [key: string]: string };
    /**
     *
     * @type {Array<ApplicationCommandCreateRequestOptionsInner>}
     * @memberof ApplicationCommandCreateRequest
     */
    options?: Array<ApplicationCommandCreateRequestOptionsInner>;
    /**
     *
     * @type {number}
     * @memberof ApplicationCommandCreateRequest
     */
    default_member_permissions?: number | null;
    /**
     *
     * @type {boolean}
     * @memberof ApplicationCommandCreateRequest
     */
    dm_permission?: boolean | null;
    /**
     *
     * @type {ApplicationCommandType}
     * @memberof ApplicationCommandCreateRequest
     */
    type?: ApplicationCommandType | null;
}
