/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandResponseOptionsInner } from "./application-command-response-options-inner";
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandType } from "./application-command-type";

/**
 *
 * @export
 * @interface ApplicationCommandResponse
 */
export interface ApplicationCommandResponse {
    /**
     *
     * @type {any}
     * @memberof ApplicationCommandResponse
     */
    id: any;
    /**
     *
     * @type {any}
     * @memberof ApplicationCommandResponse
     */
    application_id: any;
    /**
     *
     * @type {any}
     * @memberof ApplicationCommandResponse
     */
    version: any;
    /**
     *
     * @type {string}
     * @memberof ApplicationCommandResponse
     */
    default_member_permissions?: string | null;
    /**
     *
     * @type {ApplicationCommandType}
     * @memberof ApplicationCommandResponse
     */
    type: ApplicationCommandType | null;
    /**
     *
     * @type {string}
     * @memberof ApplicationCommandResponse
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof ApplicationCommandResponse
     */
    name_localized?: string | null;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof ApplicationCommandResponse
     */
    name_localizations?: { [key: string]: string };
    /**
     *
     * @type {string}
     * @memberof ApplicationCommandResponse
     */
    description: string;
    /**
     *
     * @type {string}
     * @memberof ApplicationCommandResponse
     */
    description_localized?: string | null;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof ApplicationCommandResponse
     */
    description_localizations?: { [key: string]: string };
    /**
     *
     * @type {any}
     * @memberof ApplicationCommandResponse
     */
    guild_id?: any;
    /**
     *
     * @type {boolean}
     * @memberof ApplicationCommandResponse
     */
    dm_permission?: boolean | null;
    /**
     *
     * @type {Array<ApplicationCommandResponseOptionsInner>}
     * @memberof ApplicationCommandResponse
     */
    options?: Array<ApplicationCommandResponseOptionsInner>;
    /**
     *
     * @type {boolean}
     * @memberof ApplicationCommandResponse
     */
    nsfw?: boolean | null;
}
