/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandAutocompleteCallbackRequestData } from './application-command-autocomplete-callback-request-data';
// May contain unused imports in some cases
// @ts-ignore
import { InteractionCallbackTypes } from './interaction-callback-types';

/**
 * 
 * @export
 * @interface ApplicationCommandAutocompleteCallbackRequest
 */
export interface ApplicationCommandAutocompleteCallbackRequest {
    /**
     * 
     * @type {InteractionCallbackTypes}
     * @memberof ApplicationCommandAutocompleteCallbackRequest
     */
    'type': InteractionCallbackTypes;
    /**
     * 
     * @type {ApplicationCommandAutocompleteCallbackRequestData}
     * @memberof ApplicationCommandAutocompleteCallbackRequest
     */
    'data': ApplicationCommandAutocompleteCallbackRequestData;
}

