/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandAttachmentOption } from './application-command-attachment-option';
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandBooleanOption } from './application-command-boolean-option';
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandChannelOption } from './application-command-channel-option';
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandIntegerOption } from './application-command-integer-option';
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandMentionableOption } from './application-command-mentionable-option';
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandNumberOption } from './application-command-number-option';
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandOptionType } from './application-command-option-type';
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandRoleOption } from './application-command-role-option';
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandStringOption } from './application-command-string-option';
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandSubcommandGroupOption } from './application-command-subcommand-group-option';
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandSubcommandOption } from './application-command-subcommand-option';
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandUserOption } from './application-command-user-option';

/**
 * @type ApplicationCommandCreateRequestOptionsInner
 * @export
 */
export type ApplicationCommandCreateRequestOptionsInner = ApplicationCommandAttachmentOption | ApplicationCommandBooleanOption | ApplicationCommandChannelOption | ApplicationCommandIntegerOption | ApplicationCommandMentionableOption | ApplicationCommandNumberOption | ApplicationCommandRoleOption | ApplicationCommandStringOption | ApplicationCommandSubcommandGroupOption | ApplicationCommandSubcommandOption | ApplicationCommandUserOption;


