/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandCreateRequestOptionsInner } from "./application-command-create-request-options-inner";
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandType } from "./application-command-type";

/**
 *
 * @export
 * @interface ApplicationCommandUpdateRequest
 */
export interface ApplicationCommandUpdateRequest {
  /**
   *
   * @type {string}
   * @memberof ApplicationCommandUpdateRequest
   */
  name: string;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof ApplicationCommandUpdateRequest
   */
  name_localizations?: { [key: string]: string };
  /**
   *
   * @type {string}
   * @memberof ApplicationCommandUpdateRequest
   */
  description?: string | null;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof ApplicationCommandUpdateRequest
   */
  description_localizations?: { [key: string]: string };
  /**
   *
   * @type {Array<ApplicationCommandCreateRequestOptionsInner>}
   * @memberof ApplicationCommandUpdateRequest
   */
  options?: Array<ApplicationCommandCreateRequestOptionsInner>;
  /**
   *
   * @type {number}
   * @memberof ApplicationCommandUpdateRequest
   */
  default_member_permissions?: number | null;
  /**
   *
   * @type {boolean}
   * @memberof ApplicationCommandUpdateRequest
   */
  dm_permission?: boolean | null;
  /**
   *
   * @type {ApplicationCommandType}
   * @memberof ApplicationCommandUpdateRequest
   */
  type?: ApplicationCommandType | null;
  /**
   *
   * @type {any}
   * @memberof ApplicationCommandUpdateRequest
   */
  id?: any;
}
