/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandOptionIntegerChoiceResponse } from "./application-command-option-integer-choice-response";
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandOptionType } from "./application-command-option-type";

/**
 *
 * @export
 * @interface ApplicationCommandIntegerOptionResponse
 */
export interface ApplicationCommandIntegerOptionResponse {
  /**
   *
   * @type {ApplicationCommandOptionType}
   * @memberof ApplicationCommandIntegerOptionResponse
   */
  type: ApplicationCommandOptionType | null;
  /**
   *
   * @type {string}
   * @memberof ApplicationCommandIntegerOptionResponse
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof ApplicationCommandIntegerOptionResponse
   */
  name_localized?: string | null;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof ApplicationCommandIntegerOptionResponse
   */
  name_localizations?: { [key: string]: string };
  /**
   *
   * @type {string}
   * @memberof ApplicationCommandIntegerOptionResponse
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof ApplicationCommandIntegerOptionResponse
   */
  description_localized?: string | null;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof ApplicationCommandIntegerOptionResponse
   */
  description_localizations?: { [key: string]: string };
  /**
   *
   * @type {boolean}
   * @memberof ApplicationCommandIntegerOptionResponse
   */
  required?: boolean | null;
  /**
   *
   * @type {boolean}
   * @memberof ApplicationCommandIntegerOptionResponse
   */
  autocomplete?: boolean | null;
  /**
   *
   * @type {Array<ApplicationCommandOptionIntegerChoiceResponse>}
   * @memberof ApplicationCommandIntegerOptionResponse
   */
  choices?: Array<ApplicationCommandOptionIntegerChoiceResponse>;
  /**
   *
   * @type {any}
   * @memberof ApplicationCommandIntegerOptionResponse
   */
  min_value?: any;
  /**
   *
   * @type {any}
   * @memberof ApplicationCommandIntegerOptionResponse
   */
  max_value?: any;
}
