/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ApplicationCommandOptionType } from "./application-command-option-type";

/**
 *
 * @export
 * @interface ApplicationCommandMentionableOptionResponse
 */
export interface ApplicationCommandMentionableOptionResponse {
    /**
     *
     * @type {ApplicationCommandOptionType}
     * @memberof ApplicationCommandMentionableOptionResponse
     */
    type: ApplicationCommandOptionType | null;
    /**
     *
     * @type {string}
     * @memberof ApplicationCommandMentionableOptionResponse
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof ApplicationCommandMentionableOptionResponse
     */
    name_localized?: string | null;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof ApplicationCommandMentionableOptionResponse
     */
    name_localizations?: { [key: string]: string };
    /**
     *
     * @type {string}
     * @memberof ApplicationCommandMentionableOptionResponse
     */
    description: string;
    /**
     *
     * @type {string}
     * @memberof ApplicationCommandMentionableOptionResponse
     */
    description_localized?: string | null;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof ApplicationCommandMentionableOptionResponse
     */
    description_localizations?: { [key: string]: string };
    /**
     *
     * @type {boolean}
     * @memberof ApplicationCommandMentionableOptionResponse
     */
    required?: boolean | null;
}
