/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ApplicationFormPartialDescription } from './application-form-partial-description';
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationOAuth2Params } from './application-oauth2-params';
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationTypes } from './application-types';

/**
 * 
 * @export
 * @interface ApplicationFormPartial
 */
export interface ApplicationFormPartial {
    /**
     * 
     * @type {ApplicationFormPartialDescription}
     * @memberof ApplicationFormPartial
     */
    'description'?: ApplicationFormPartialDescription;
    /**
     * 
     * @type {string}
     * @memberof ApplicationFormPartial
     */
    'icon'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApplicationFormPartial
     */
    'cover_image'?: string | null;
    /**
     * 
     * @type {any}
     * @memberof ApplicationFormPartial
     */
    'team_id'?: any;
    /**
     * 
     * @type {number}
     * @memberof ApplicationFormPartial
     */
    'flags'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ApplicationFormPartial
     */
    'interactions_endpoint_url'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApplicationFormPartial
     */
    'max_participants'?: number | null;
    /**
     * 
     * @type {ApplicationTypes}
     * @memberof ApplicationFormPartial
     */
    'type'?: ApplicationTypes | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApplicationFormPartial
     */
    'tags'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ApplicationFormPartial
     */
    'custom_install_url'?: string | null;
    /**
     * 
     * @type {ApplicationOAuth2Params}
     * @memberof ApplicationFormPartial
     */
    'install_params'?: ApplicationOAuth2Params | null;
    /**
     * 
     * @type {string}
     * @memberof ApplicationFormPartial
     */
    'role_connections_verification_url'?: string | null;
}

