/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AuditLogActionTypes } from "./audit-log-action-types";
// May contain unused imports in some cases
// @ts-ignore
import { AuditLogObjectChangeResponse } from "./audit-log-object-change-response";

/**
 *
 * @export
 * @interface AuditLogEntryResponse
 */
export interface AuditLogEntryResponse {
  /**
   *
   * @type {any}
   * @memberof AuditLogEntryResponse
   */
  id: any;
  /**
   *
   * @type {AuditLogActionTypes}
   * @memberof AuditLogEntryResponse
   */
  action_type: AuditLogActionTypes | null;
  /**
   *
   * @type {any}
   * @memberof AuditLogEntryResponse
   */
  user_id?: any;
  /**
   *
   * @type {any}
   * @memberof AuditLogEntryResponse
   */
  target_id?: any;
  /**
   *
   * @type {Array<AuditLogObjectChangeResponse>}
   * @memberof AuditLogEntryResponse
   */
  changes?: Array<AuditLogObjectChangeResponse>;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof AuditLogEntryResponse
   */
  options?: { [key: string]: string };
  /**
   *
   * @type {string}
   * @memberof AuditLogEntryResponse
   */
  reason?: string | null;
}
