/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ChannelTypes } from "./channel-types";
// May contain unused imports in some cases
// @ts-ignore
import { CreateGuildChannelRequestVideoQualityMode } from "./create-guild-channel-request-video-quality-mode";
// May contain unused imports in some cases
// @ts-ignore
import { CreatedThreadResponseMember } from "./created-thread-response-member";
// May contain unused imports in some cases
// @ts-ignore
import { CreatedThreadResponseThreadMetadata } from "./created-thread-response-thread-metadata";
// May contain unused imports in some cases
// @ts-ignore
import { ThreadResponse } from "./thread-response";
// May contain unused imports in some cases
// @ts-ignore
import { UpdateSelfVoiceStateRequestChannelId } from "./update-self-voice-state-request-channel-id";

/**
 * @type BasicMessageResponseThread
 * @export
 */
export type BasicMessageResponseThread = ThreadResponse | any;
