/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GuildMemberResponse } from './guild-member-response';
// May contain unused imports in some cases
// @ts-ignore
import { GuildRoleResponse } from './guild-role-response';
// May contain unused imports in some cases
// @ts-ignore
import { ListGuildChannels200ResponseInner } from './list-guild-channels200-response-inner';
// May contain unused imports in some cases
// @ts-ignore
import { ResolvedObjectsResponse } from './resolved-objects-response';
// May contain unused imports in some cases
// @ts-ignore
import { UserResponse } from './user-response';

/**
 * @type BasicMessageResponseResolved
 * @export
 */
export type BasicMessageResponseResolved = ResolvedObjectsResponse | any;


