/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseActivity } from "./basic-message-response-activity";
// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseApplication } from "./basic-message-response-application";
// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseApplicationId } from "./basic-message-response-application-id";
// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseInteraction } from "./basic-message-response-interaction";
// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseMessageReference } from "./basic-message-response-message-reference";
// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseNonce } from "./basic-message-response-nonce";
// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponsePurchaseNotification } from "./basic-message-response-purchase-notification";
// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseResolved } from "./basic-message-response-resolved";
// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseRoleSubscriptionData } from "./basic-message-response-role-subscription-data";
// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseThread } from "./basic-message-response-thread";
// May contain unused imports in some cases
// @ts-ignore
import { MessageType } from "./message-type";
// May contain unused imports in some cases
// @ts-ignore
import { UserResponse } from "./user-response";

/**
 *
 * @export
 * @interface BasicMessageResponse
 */
export interface BasicMessageResponse {
    /**
     *
     * @type {any}
     * @memberof BasicMessageResponse
     */
    id: any;
    /**
     *
     * @type {MessageType}
     * @memberof BasicMessageResponse
     */
    type: MessageType;
    /**
     *
     * @type {any}
     * @memberof BasicMessageResponse
     */
    content: any;
    /**
     *
     * @type {any}
     * @memberof BasicMessageResponse
     */
    channel_id: any;
    /**
     *
     * @type {UserResponse}
     * @memberof BasicMessageResponse
     */
    author: UserResponse;
    /**
     *
     * @type {any}
     * @memberof BasicMessageResponse
     */
    attachments: any;
    /**
     *
     * @type {any}
     * @memberof BasicMessageResponse
     */
    embeds: any;
    /**
     *
     * @type {any}
     * @memberof BasicMessageResponse
     */
    mentions: any;
    /**
     *
     * @type {any}
     * @memberof BasicMessageResponse
     */
    mention_roles: any;
    /**
     *
     * @type {any}
     * @memberof BasicMessageResponse
     */
    pinned: any;
    /**
     *
     * @type {any}
     * @memberof BasicMessageResponse
     */
    mention_everyone: any;
    /**
     *
     * @type {any}
     * @memberof BasicMessageResponse
     */
    tts: any;
    /**
     *
     * @type {any}
     * @memberof BasicMessageResponse
     */
    timestamp: any;
    /**
     *
     * @type {any}
     * @memberof BasicMessageResponse
     */
    edited_timestamp?: any;
    /**
     *
     * @type {any}
     * @memberof BasicMessageResponse
     */
    flags: any;
    /**
     *
     * @type {any}
     * @memberof BasicMessageResponse
     */
    components: any;
    /**
     *
     * @type {BasicMessageResponseActivity}
     * @memberof BasicMessageResponse
     */
    activity?: BasicMessageResponseActivity;
    /**
     *
     * @type {BasicMessageResponseApplication}
     * @memberof BasicMessageResponse
     */
    application?: BasicMessageResponseApplication;
    /**
     *
     * @type {BasicMessageResponseApplicationId}
     * @memberof BasicMessageResponse
     */
    application_id?: BasicMessageResponseApplicationId;
    /**
     *
     * @type {BasicMessageResponseInteraction}
     * @memberof BasicMessageResponse
     */
    interaction?: BasicMessageResponseInteraction;
    /**
     *
     * @type {BasicMessageResponseNonce}
     * @memberof BasicMessageResponse
     */
    nonce?: BasicMessageResponseNonce;
    /**
     *
     * @type {BasicMessageResponseApplicationId}
     * @memberof BasicMessageResponse
     */
    webhook_id?: BasicMessageResponseApplicationId;
    /**
     *
     * @type {BasicMessageResponseMessageReference}
     * @memberof BasicMessageResponse
     */
    message_reference?: BasicMessageResponseMessageReference;
    /**
     *
     * @type {BasicMessageResponseThread}
     * @memberof BasicMessageResponse
     */
    thread?: BasicMessageResponseThread;
    /**
     *
     * @type {any}
     * @memberof BasicMessageResponse
     */
    mention_channels?: any;
    /**
     *
     * @type {any}
     * @memberof BasicMessageResponse
     */
    stickers?: any;
    /**
     *
     * @type {any}
     * @memberof BasicMessageResponse
     */
    sticker_items?: any;
    /**
     *
     * @type {BasicMessageResponseRoleSubscriptionData}
     * @memberof BasicMessageResponse
     */
    role_subscription_data?: BasicMessageResponseRoleSubscriptionData;
    /**
     *
     * @type {BasicMessageResponsePurchaseNotification}
     * @memberof BasicMessageResponse
     */
    purchase_notification?: BasicMessageResponsePurchaseNotification;
    /**
     *
     * @type {any}
     * @memberof BasicMessageResponse
     */
    position?: any;
    /**
     *
     * @type {BasicMessageResponseResolved}
     * @memberof BasicMessageResponse
     */
    resolved?: BasicMessageResponseResolved;
}
