/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ButtonEmoji } from "./button-emoji";
// May contain unused imports in some cases
// @ts-ignore
import { ButtonStyleTypes } from "./button-style-types";
// May contain unused imports in some cases
// @ts-ignore
import { MessageComponentTypes } from "./message-component-types";

/**
 *
 * @export
 * @interface Button
 */
export interface Button {
    /**
     *
     * @type {MessageComponentTypes}
     * @memberof Button
     */
    type: MessageComponentTypes;
    /**
     *
     * @type {any}
     * @memberof Button
     */
    custom_id?: any;
    /**
     *
     * @type {ButtonStyleTypes}
     * @memberof Button
     */
    style: ButtonStyleTypes;
    /**
     *
     * @type {any}
     * @memberof Button
     */
    label?: any;
    /**
     *
     * @type {any}
     * @memberof Button
     */
    disabled?: any;
    /**
     *
     * @type {ButtonEmoji}
     * @memberof Button
     */
    emoji?: ButtonEmoji;
    /**
     *
     * @type {any}
     * @memberof Button
     */
    url?: any;
}
