/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseApplicationId } from "./basic-message-response-application-id";
// May contain unused imports in some cases
// @ts-ignore
import { ChannelFollowerWebhookResponseSourceChannel } from "./channel-follower-webhook-response-source-channel";
// May contain unused imports in some cases
// @ts-ignore
import { ChannelFollowerWebhookResponseSourceGuild } from "./channel-follower-webhook-response-source-guild";
// May contain unused imports in some cases
// @ts-ignore
import { ChannelFollowerWebhookResponseUser } from "./channel-follower-webhook-response-user";
// May contain unused imports in some cases
// @ts-ignore
import { WebhookTypes } from "./webhook-types";

/**
 *
 * @export
 * @interface ChannelFollowerWebhookResponse
 */
export interface ChannelFollowerWebhookResponse {
    /**
     *
     * @type {BasicMessageResponseApplicationId}
     * @memberof ChannelFollowerWebhookResponse
     */
    application_id?: BasicMessageResponseApplicationId;
    /**
     *
     * @type {any}
     * @memberof ChannelFollowerWebhookResponse
     */
    avatar?: any;
    /**
     *
     * @type {BasicMessageResponseApplicationId}
     * @memberof ChannelFollowerWebhookResponse
     */
    channel_id?: BasicMessageResponseApplicationId;
    /**
     *
     * @type {BasicMessageResponseApplicationId}
     * @memberof ChannelFollowerWebhookResponse
     */
    guild_id?: BasicMessageResponseApplicationId;
    /**
     *
     * @type {any}
     * @memberof ChannelFollowerWebhookResponse
     */
    id: any;
    /**
     *
     * @type {any}
     * @memberof ChannelFollowerWebhookResponse
     */
    name: any;
    /**
     *
     * @type {WebhookTypes}
     * @memberof ChannelFollowerWebhookResponse
     */
    type: WebhookTypes;
    /**
     *
     * @type {ChannelFollowerWebhookResponseUser}
     * @memberof ChannelFollowerWebhookResponse
     */
    user?: ChannelFollowerWebhookResponseUser;
    /**
     *
     * @type {ChannelFollowerWebhookResponseSourceGuild}
     * @memberof ChannelFollowerWebhookResponse
     */
    source_guild?: ChannelFollowerWebhookResponseSourceGuild;
    /**
     *
     * @type {ChannelFollowerWebhookResponseSourceChannel}
     * @memberof ChannelFollowerWebhookResponse
     */
    source_channel?: ChannelFollowerWebhookResponseSourceChannel;
}
