/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ConnectedAccountGuildResponse
 */
export interface ConnectedAccountGuildResponse {
  /**
   *
   * @type {any}
   * @memberof ConnectedAccountGuildResponse
   */
  id: any;
  /**
   *
   * @type {string}
   * @memberof ConnectedAccountGuildResponse
   */
  name: string | null;
  /**
   *
   * @type {string}
   * @memberof ConnectedAccountGuildResponse
   */
  icon?: string | null;
}
