/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ConnectedAccountProviders } from './connected-account-providers';
// May contain unused imports in some cases
// @ts-ignore
import { ConnectedAccountVisibility } from './connected-account-visibility';

/**
 * 
 * @export
 * @interface ConnectedAccountResponse
 */
export interface ConnectedAccountResponse {
    /**
     * 
     * @type {any}
     * @memberof ConnectedAccountResponse
     */
    'id': any;
    /**
     * 
     * @type {any}
     * @memberof ConnectedAccountResponse
     */
    'name'?: any;
    /**
     * 
     * @type {ConnectedAccountProviders}
     * @memberof ConnectedAccountResponse
     */
    'type': ConnectedAccountProviders;
    /**
     * 
     * @type {any}
     * @memberof ConnectedAccountResponse
     */
    'friend_sync': any;
    /**
     * 
     * @type {any}
     * @memberof ConnectedAccountResponse
     */
    'integrations'?: any;
    /**
     * 
     * @type {any}
     * @memberof ConnectedAccountResponse
     */
    'show_activity': any;
    /**
     * 
     * @type {any}
     * @memberof ConnectedAccountResponse
     */
    'two_way_link': any;
    /**
     * 
     * @type {any}
     * @memberof ConnectedAccountResponse
     */
    'verified': any;
    /**
     * 
     * @type {ConnectedAccountVisibility}
     * @memberof ConnectedAccountResponse
     */
    'visibility': ConnectedAccountVisibility;
    /**
     * 
     * @type {any}
     * @memberof ConnectedAccountResponse
     */
    'revoked'?: any;
}

