/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateGuildRequestRoleItem
 */
export interface CreateGuildRequestRoleItem {
  /**
   *
   * @type {any}
   * @memberof CreateGuildRequestRoleItem
   */
  id: any;
  /**
   *
   * @type {any}
   * @memberof CreateGuildRequestRoleItem
   */
  name?: any;
  /**
   *
   * @type {any}
   * @memberof CreateGuildRequestRoleItem
   */
  permissions?: any;
  /**
   *
   * @type {any}
   * @memberof CreateGuildRequestRoleItem
   */
  color?: any;
  /**
   *
   * @type {any}
   * @memberof CreateGuildRequestRoleItem
   */
  hoist?: any;
  /**
   *
   * @type {any}
   * @memberof CreateGuildRequestRoleItem
   */
  mentionable?: any;
  /**
   *
   * @type {any}
   * @memberof CreateGuildRequestRoleItem
   */
  unicode_emoji?: any;
}
