/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { CreateForumThreadRequestAutoArchiveDuration } from "./create-forum-thread-request-auto-archive-duration";

/**
 *
 * @export
 * @interface CreateTextThreadWithMessageRequest
 */
export interface CreateTextThreadWithMessageRequest {
    /**
     *
     * @type {any}
     * @memberof CreateTextThreadWithMessageRequest
     */
    name: any;
    /**
     *
     * @type {CreateForumThreadRequestAutoArchiveDuration}
     * @memberof CreateTextThreadWithMessageRequest
     */
    auto_archive_duration?: CreateForumThreadRequestAutoArchiveDuration;
    /**
     *
     * @type {any}
     * @memberof CreateTextThreadWithMessageRequest
     */
    rate_limit_per_user?: any;
}
