/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseApplicationId } from "./basic-message-response-application-id";
// May contain unused imports in some cases
// @ts-ignore
import { ExternalScheduledEventCreateRequest } from "./external-scheduled-event-create-request";
// May contain unused imports in some cases
// @ts-ignore
import { GuildScheduledEventEntityTypes } from "./guild-scheduled-event-entity-types";
// May contain unused imports in some cases
// @ts-ignore
import { GuildScheduledEventPrivacyLevels } from "./guild-scheduled-event-privacy-levels";
// May contain unused imports in some cases
// @ts-ignore
import { StageScheduledEventCreateRequest } from "./stage-scheduled-event-create-request";
// May contain unused imports in some cases
// @ts-ignore
import { VoiceScheduledEventCreateRequest } from "./voice-scheduled-event-create-request";
// May contain unused imports in some cases
// @ts-ignore
import { VoiceScheduledEventCreateRequestEntityMetadata } from "./voice-scheduled-event-create-request-entity-metadata";

/**
 * @type CreateGuildScheduledEventRequest
 * @export
 */
export type CreateGuildScheduledEventRequest =
    | ExternalScheduledEventCreateRequest
    | StageScheduledEventCreateRequest
    | VoiceScheduledEventCreateRequest;
