/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BaseCreateMessageCreateRequest } from './base-create-message-create-request';
// May contain unused imports in some cases
// @ts-ignore
import { CreateForumThreadRequest } from './create-forum-thread-request';
// May contain unused imports in some cases
// @ts-ignore
import { CreateForumThreadRequestAutoArchiveDuration } from './create-forum-thread-request-auto-archive-duration';
// May contain unused imports in some cases
// @ts-ignore
import { CreateTextThreadWithoutMessageRequest } from './create-text-thread-without-message-request';
// May contain unused imports in some cases
// @ts-ignore
import { CreateTextThreadWithoutMessageRequestType } from './create-text-thread-without-message-request-type';

/**
 * 
 * @export
 * @interface CreateThreadRequest
 */
export interface CreateThreadRequest {
    /**
     * 
     * @type {any}
     * @memberof CreateThreadRequest
     */
    'name': any;
    /**
     * 
     * @type {CreateForumThreadRequestAutoArchiveDuration}
     * @memberof CreateThreadRequest
     */
    'auto_archive_duration'?: CreateForumThreadRequestAutoArchiveDuration;
    /**
     * 
     * @type {any}
     * @memberof CreateThreadRequest
     */
    'rate_limit_per_user'?: any;
    /**
     * 
     * @type {any}
     * @memberof CreateThreadRequest
     */
    'applied_tags'?: any;
    /**
     * 
     * @type {BaseCreateMessageCreateRequest}
     * @memberof CreateThreadRequest
     */
    'message': BaseCreateMessageCreateRequest;
    /**
     * 
     * @type {CreateTextThreadWithoutMessageRequestType}
     * @memberof CreateThreadRequest
     */
    'type'?: CreateTextThreadWithoutMessageRequestType;
    /**
     * 
     * @type {any}
     * @memberof CreateThreadRequest
     */
    'invitable'?: any;
}

