/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { StageInstancesPrivacyLevels } from "./stage-instances-privacy-levels";

/**
 *
 * @export
 * @interface CreateStageInstanceRequest
 */
export interface CreateStageInstanceRequest {
    /**
     *
     * @type {string}
     * @memberof CreateStageInstanceRequest
     */
    topic: string;
    /**
     *
     * @type {any}
     * @memberof CreateStageInstanceRequest
     */
    channel_id: any;
    /**
     *
     * @type {StageInstancesPrivacyLevels}
     * @memberof CreateStageInstanceRequest
     */
    privacy_level?: StageInstancesPrivacyLevels | null;
    /**
     *
     * @type {any}
     * @memberof CreateStageInstanceRequest
     */
    guild_scheduled_event_id?: any;
    /**
     *
     * @type {boolean}
     * @memberof CreateStageInstanceRequest
     */
    send_start_notification?: boolean | null;
}
