/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseApplicationId } from './basic-message-response-application-id';
// May contain unused imports in some cases
// @ts-ignore
import { CreateForumThreadRequestAutoArchiveDuration } from './create-forum-thread-request-auto-archive-duration';
// May contain unused imports in some cases
// @ts-ignore
import { CreateGuildChannelRequestDefaultForumLayout } from './create-guild-channel-request-default-forum-layout';
// May contain unused imports in some cases
// @ts-ignore
import { CreateGuildChannelRequestDefaultReactionEmoji } from './create-guild-channel-request-default-reaction-emoji';
// May contain unused imports in some cases
// @ts-ignore
import { CreateGuildChannelRequestDefaultSortOrder } from './create-guild-channel-request-default-sort-order';
// May contain unused imports in some cases
// @ts-ignore
import { CreateGuildChannelRequestType } from './create-guild-channel-request-type';
// May contain unused imports in some cases
// @ts-ignore
import { CreateGuildChannelRequestVideoQualityMode } from './create-guild-channel-request-video-quality-mode';

/**
 * 
 * @export
 * @interface CreateGuildChannelRequest
 */
export interface CreateGuildChannelRequest {
    /**
     * 
     * @type {CreateGuildChannelRequestType}
     * @memberof CreateGuildChannelRequest
     */
    'type'?: CreateGuildChannelRequestType;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildChannelRequest
     */
    'name': any;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildChannelRequest
     */
    'position'?: any;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildChannelRequest
     */
    'topic'?: any;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildChannelRequest
     */
    'bitrate'?: any;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildChannelRequest
     */
    'user_limit'?: any;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildChannelRequest
     */
    'nsfw'?: any;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildChannelRequest
     */
    'rate_limit_per_user'?: any;
    /**
     * 
     * @type {BasicMessageResponseApplicationId}
     * @memberof CreateGuildChannelRequest
     */
    'parent_id'?: BasicMessageResponseApplicationId;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildChannelRequest
     */
    'permission_overwrites'?: any;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildChannelRequest
     */
    'rtc_region'?: any;
    /**
     * 
     * @type {CreateGuildChannelRequestVideoQualityMode}
     * @memberof CreateGuildChannelRequest
     */
    'video_quality_mode'?: CreateGuildChannelRequestVideoQualityMode;
    /**
     * 
     * @type {CreateForumThreadRequestAutoArchiveDuration}
     * @memberof CreateGuildChannelRequest
     */
    'default_auto_archive_duration'?: CreateForumThreadRequestAutoArchiveDuration;
    /**
     * 
     * @type {CreateGuildChannelRequestDefaultReactionEmoji}
     * @memberof CreateGuildChannelRequest
     */
    'default_reaction_emoji'?: CreateGuildChannelRequestDefaultReactionEmoji;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildChannelRequest
     */
    'default_thread_rate_limit_per_user'?: any;
    /**
     * 
     * @type {CreateGuildChannelRequestDefaultSortOrder}
     * @memberof CreateGuildChannelRequest
     */
    'default_sort_order'?: CreateGuildChannelRequestDefaultSortOrder;
    /**
     * 
     * @type {CreateGuildChannelRequestDefaultForumLayout}
     * @memberof CreateGuildChannelRequest
     */
    'default_forum_layout'?: CreateGuildChannelRequestDefaultForumLayout;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildChannelRequest
     */
    'available_tags'?: any;
}

