/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ChannelFollowerWebhookResponseUser } from "./channel-follower-webhook-response-user";
// May contain unused imports in some cases
// @ts-ignore
import { DiscordIntegrationResponseAccount } from "./discord-integration-response-account";
// May contain unused imports in some cases
// @ts-ignore
import { IntegrationApplicationResponse } from "./integration-application-response";
// May contain unused imports in some cases
// @ts-ignore
import { IntegrationTypes } from "./integration-types";

/**
 *
 * @export
 * @interface DiscordIntegrationResponse
 */
export interface DiscordIntegrationResponse {
  /**
   *
   * @type {IntegrationTypes}
   * @memberof DiscordIntegrationResponse
   */
  type: IntegrationTypes;
  /**
   *
   * @type {any}
   * @memberof DiscordIntegrationResponse
   */
  name?: any;
  /**
   *
   * @type {DiscordIntegrationResponseAccount}
   * @memberof DiscordIntegrationResponse
   */
  account?: DiscordIntegrationResponseAccount;
  /**
   *
   * @type {any}
   * @memberof DiscordIntegrationResponse
   */
  enabled?: any;
  /**
   *
   * @type {any}
   * @memberof DiscordIntegrationResponse
   */
  id: any;
  /**
   *
   * @type {IntegrationApplicationResponse}
   * @memberof DiscordIntegrationResponse
   */
  application: IntegrationApplicationResponse;
  /**
   *
   * @type {any}
   * @memberof DiscordIntegrationResponse
   */
  scopes: any;
  /**
   *
   * @type {ChannelFollowerWebhookResponseUser}
   * @memberof DiscordIntegrationResponse
   */
  user?: ChannelFollowerWebhookResponseUser;
}
