/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ChannelFollowerWebhookResponseUser } from "./channel-follower-webhook-response-user";

/**
 *
 * @export
 * @interface EmojiResponse
 */
export interface EmojiResponse {
  /**
   *
   * @type {any}
   * @memberof EmojiResponse
   */
  id: any;
  /**
   *
   * @type {any}
   * @memberof EmojiResponse
   */
  name: any;
  /**
   *
   * @type {ChannelFollowerWebhookResponseUser}
   * @memberof EmojiResponse
   */
  user?: ChannelFollowerWebhookResponseUser;
  /**
   *
   * @type {any}
   * @memberof EmojiResponse
   */
  roles: any;
  /**
   *
   * @type {any}
   * @memberof EmojiResponse
   */
  require_colons: any;
  /**
   *
   * @type {any}
   * @memberof EmojiResponse
   */
  managed: any;
  /**
   *
   * @type {any}
   * @memberof EmojiResponse
   */
  animated: any;
  /**
   *
   * @type {any}
   * @memberof EmojiResponse
   */
  available: any;
}
