/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { BaseCreateMessageCreateRequestAllowedMentions } from "./base-create-message-create-request-allowed-mentions";
// May contain unused imports in some cases
// @ts-ignore
import { IncomingWebhookRequestPartial } from "./incoming-webhook-request-partial";
// May contain unused imports in some cases
// @ts-ignore
import { IncomingWebhookUpdateRequestPartial } from "./incoming-webhook-update-request-partial";

/**
 *
 * @export
 * @interface ExecuteWebhookRequest
 */
export interface ExecuteWebhookRequest {
    /**
     *
     * @type {any}
     * @memberof ExecuteWebhookRequest
     */
    content?: any;
    /**
     *
     * @type {any}
     * @memberof ExecuteWebhookRequest
     */
    embeds?: any;
    /**
     *
     * @type {BaseCreateMessageCreateRequestAllowedMentions}
     * @memberof ExecuteWebhookRequest
     */
    allowed_mentions?: BaseCreateMessageCreateRequestAllowedMentions;
    /**
     *
     * @type {any}
     * @memberof ExecuteWebhookRequest
     */
    components?: any;
    /**
     *
     * @type {any}
     * @memberof ExecuteWebhookRequest
     */
    attachments?: any;
    /**
     *
     * @type {any}
     * @memberof ExecuteWebhookRequest
     */
    tts?: any;
    /**
     *
     * @type {any}
     * @memberof ExecuteWebhookRequest
     */
    flags?: any;
    /**
     *
     * @type {any}
     * @memberof ExecuteWebhookRequest
     */
    username?: any;
    /**
     *
     * @type {any}
     * @memberof ExecuteWebhookRequest
     */
    avatar_url?: any;
    /**
     *
     * @type {any}
     * @memberof ExecuteWebhookRequest
     */
    thread_name?: any;
    /**
     *
     * @type {any}
     * @memberof ExecuteWebhookRequest
     */
    applied_tags?: any;
}
