/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseApplicationId } from "./basic-message-response-application-id";
// May contain unused imports in some cases
// @ts-ignore
import { DiscordIntegrationResponseAccount } from "./discord-integration-response-account";
// May contain unused imports in some cases
// @ts-ignore
import { ExternalConnectionIntegrationResponseExpireBehavior } from "./external-connection-integration-response-expire-behavior";
// May contain unused imports in some cases
// @ts-ignore
import { ExternalConnectionIntegrationResponseExpireGracePeriod } from "./external-connection-integration-response-expire-grace-period";
// May contain unused imports in some cases
// @ts-ignore
import { IntegrationTypes } from "./integration-types";
// May contain unused imports in some cases
// @ts-ignore
import { UserResponse } from "./user-response";

/**
 *
 * @export
 * @interface ExternalConnectionIntegrationResponse
 */
export interface ExternalConnectionIntegrationResponse {
  /**
   *
   * @type {IntegrationTypes}
   * @memberof ExternalConnectionIntegrationResponse
   */
  type: IntegrationTypes;
  /**
   *
   * @type {any}
   * @memberof ExternalConnectionIntegrationResponse
   */
  name?: any;
  /**
   *
   * @type {DiscordIntegrationResponseAccount}
   * @memberof ExternalConnectionIntegrationResponse
   */
  account?: DiscordIntegrationResponseAccount;
  /**
   *
   * @type {any}
   * @memberof ExternalConnectionIntegrationResponse
   */
  enabled?: any;
  /**
   *
   * @type {any}
   * @memberof ExternalConnectionIntegrationResponse
   */
  id: any;
  /**
   *
   * @type {UserResponse}
   * @memberof ExternalConnectionIntegrationResponse
   */
  user: UserResponse;
  /**
   *
   * @type {any}
   * @memberof ExternalConnectionIntegrationResponse
   */
  revoked?: any;
  /**
   *
   * @type {ExternalConnectionIntegrationResponseExpireBehavior}
   * @memberof ExternalConnectionIntegrationResponse
   */
  expire_behavior?: ExternalConnectionIntegrationResponseExpireBehavior;
  /**
   *
   * @type {ExternalConnectionIntegrationResponseExpireGracePeriod}
   * @memberof ExternalConnectionIntegrationResponse
   */
  expire_grace_period?: ExternalConnectionIntegrationResponseExpireGracePeriod;
  /**
   *
   * @type {any}
   * @memberof ExternalConnectionIntegrationResponse
   */
  subscriber_count?: any;
  /**
   *
   * @type {any}
   * @memberof ExternalConnectionIntegrationResponse
   */
  synced_at?: any;
  /**
   *
   * @type {BasicMessageResponseApplicationId}
   * @memberof ExternalConnectionIntegrationResponse
   */
  role_id?: BasicMessageResponseApplicationId;
  /**
   *
   * @type {any}
   * @memberof ExternalConnectionIntegrationResponse
   */
  syncing?: any;
  /**
   *
   * @type {any}
   * @memberof ExternalConnectionIntegrationResponse
   */
  enable_emoticons?: any;
}
