/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseApplicationId } from "./basic-message-response-application-id";
// May contain unused imports in some cases
// @ts-ignore
import { ChannelFollowerWebhookResponseUser } from "./channel-follower-webhook-response-user";
// May contain unused imports in some cases
// @ts-ignore
import { EntityMetadataExternalResponse } from "./entity-metadata-external-response";
// May contain unused imports in some cases
// @ts-ignore
import { ExternalScheduledEventResponseUserRsvp } from "./external-scheduled-event-response-user-rsvp";
// May contain unused imports in some cases
// @ts-ignore
import { GuildScheduledEventEntityTypes } from "./guild-scheduled-event-entity-types";
// May contain unused imports in some cases
// @ts-ignore
import { GuildScheduledEventPrivacyLevels } from "./guild-scheduled-event-privacy-levels";
// May contain unused imports in some cases
// @ts-ignore
import { GuildScheduledEventStatuses } from "./guild-scheduled-event-statuses";

/**
 *
 * @export
 * @interface ExternalScheduledEventResponse
 */
export interface ExternalScheduledEventResponse {
  /**
   *
   * @type {any}
   * @memberof ExternalScheduledEventResponse
   */
  id: any;
  /**
   *
   * @type {any}
   * @memberof ExternalScheduledEventResponse
   */
  guild_id: any;
  /**
   *
   * @type {any}
   * @memberof ExternalScheduledEventResponse
   */
  name: any;
  /**
   *
   * @type {any}
   * @memberof ExternalScheduledEventResponse
   */
  description?: any;
  /**
   *
   * @type {BasicMessageResponseApplicationId}
   * @memberof ExternalScheduledEventResponse
   */
  channel_id?: BasicMessageResponseApplicationId;
  /**
   *
   * @type {BasicMessageResponseApplicationId}
   * @memberof ExternalScheduledEventResponse
   */
  creator_id?: BasicMessageResponseApplicationId;
  /**
   *
   * @type {ChannelFollowerWebhookResponseUser}
   * @memberof ExternalScheduledEventResponse
   */
  creator?: ChannelFollowerWebhookResponseUser;
  /**
   *
   * @type {any}
   * @memberof ExternalScheduledEventResponse
   */
  image?: any;
  /**
   *
   * @type {any}
   * @memberof ExternalScheduledEventResponse
   */
  scheduled_start_time: any;
  /**
   *
   * @type {any}
   * @memberof ExternalScheduledEventResponse
   */
  scheduled_end_time?: any;
  /**
   *
   * @type {GuildScheduledEventStatuses}
   * @memberof ExternalScheduledEventResponse
   */
  status: GuildScheduledEventStatuses;
  /**
   *
   * @type {GuildScheduledEventEntityTypes}
   * @memberof ExternalScheduledEventResponse
   */
  entity_type: GuildScheduledEventEntityTypes;
  /**
   *
   * @type {BasicMessageResponseApplicationId}
   * @memberof ExternalScheduledEventResponse
   */
  entity_id?: BasicMessageResponseApplicationId;
  /**
   *
   * @type {any}
   * @memberof ExternalScheduledEventResponse
   */
  user_count?: any;
  /**
   *
   * @type {GuildScheduledEventPrivacyLevels}
   * @memberof ExternalScheduledEventResponse
   */
  privacy_level: GuildScheduledEventPrivacyLevels;
  /**
   *
   * @type {ExternalScheduledEventResponseUserRsvp}
   * @memberof ExternalScheduledEventResponse
   */
  user_rsvp?: ExternalScheduledEventResponseUserRsvp;
  /**
   *
   * @type {EntityMetadataExternalResponse}
   * @memberof ExternalScheduledEventResponse
   */
  entity_metadata: EntityMetadataExternalResponse;
}
