/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ChannelFollowerWebhookResponseUser } from './channel-follower-webhook-response-user';
// May contain unused imports in some cases
// @ts-ignore
import { FriendInviteResponseChannel } from './friend-invite-response-channel';
// May contain unused imports in some cases
// @ts-ignore
import { FriendInviteResponseType } from './friend-invite-response-type';

/**
 * 
 * @export
 * @interface FriendInviteResponse
 */
export interface FriendInviteResponse {
    /**
     * 
     * @type {FriendInviteResponseType}
     * @memberof FriendInviteResponse
     */
    'type'?: FriendInviteResponseType;
    /**
     * 
     * @type {any}
     * @memberof FriendInviteResponse
     */
    'code': any;
    /**
     * 
     * @type {ChannelFollowerWebhookResponseUser}
     * @memberof FriendInviteResponse
     */
    'inviter'?: ChannelFollowerWebhookResponseUser;
    /**
     * 
     * @type {any}
     * @memberof FriendInviteResponse
     */
    'max_age'?: any;
    /**
     * 
     * @type {any}
     * @memberof FriendInviteResponse
     */
    'created_at'?: any;
    /**
     * 
     * @type {any}
     * @memberof FriendInviteResponse
     */
    'expires_at'?: any;
    /**
     * 
     * @type {any}
     * @memberof FriendInviteResponse
     */
    'friends_count'?: any;
    /**
     * 
     * @type {FriendInviteResponseChannel}
     * @memberof FriendInviteResponse
     */
    'channel'?: FriendInviteResponseChannel;
    /**
     * 
     * @type {any}
     * @memberof FriendInviteResponse
     */
    'is_contact'?: any;
    /**
     * 
     * @type {any}
     * @memberof FriendInviteResponse
     */
    'uses'?: any;
    /**
     * 
     * @type {any}
     * @memberof FriendInviteResponse
     */
    'max_uses'?: any;
    /**
     * 
     * @type {any}
     * @memberof FriendInviteResponse
     */
    'flags'?: any;
}

