/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseApplicationId } from "./basic-message-response-application-id";
// May contain unused imports in some cases
// @ts-ignore
import { ChannelFollowerWebhookResponseUser } from "./channel-follower-webhook-response-user";
// May contain unused imports in some cases
// @ts-ignore
import { ExternalScheduledEventResponse } from "./external-scheduled-event-response";
// May contain unused imports in some cases
// @ts-ignore
import { ExternalScheduledEventResponseUserRsvp } from "./external-scheduled-event-response-user-rsvp";
// May contain unused imports in some cases
// @ts-ignore
import { GuildScheduledEventEntityTypes } from "./guild-scheduled-event-entity-types";
// May contain unused imports in some cases
// @ts-ignore
import { GuildScheduledEventPrivacyLevels } from "./guild-scheduled-event-privacy-levels";
// May contain unused imports in some cases
// @ts-ignore
import { GuildScheduledEventStatuses } from "./guild-scheduled-event-statuses";
// May contain unused imports in some cases
// @ts-ignore
import { StageScheduledEventResponse } from "./stage-scheduled-event-response";
// May contain unused imports in some cases
// @ts-ignore
import { VoiceScheduledEventResponse } from "./voice-scheduled-event-response";
// May contain unused imports in some cases
// @ts-ignore
import { VoiceScheduledEventResponseEntityMetadata } from "./voice-scheduled-event-response-entity-metadata";

/**
 * @type GetGuildScheduledEvent200Response
 * @export
 */
export type GetGuildScheduledEvent200Response =
  | ExternalScheduledEventResponse
  | StageScheduledEventResponse
  | VoiceScheduledEventResponse;
