/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ChannelFollowerWebhookResponseUser } from './channel-follower-webhook-response-user';
// May contain unused imports in some cases
// @ts-ignore
import { GuildStickerResponse } from './guild-sticker-response';
// May contain unused imports in some cases
// @ts-ignore
import { GuildStickerResponseFormatType } from './guild-sticker-response-format-type';
// May contain unused imports in some cases
// @ts-ignore
import { StandardStickerResponse } from './standard-sticker-response';
// May contain unused imports in some cases
// @ts-ignore
import { StickerTypes } from './sticker-types';

/**
 * @type GetSticker200Response
 * @export
 */
export type GetSticker200Response = GuildStickerResponse | StandardStickerResponse;


