/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GithubAuthor } from './github-author';

/**
 * 
 * @export
 * @interface GithubCommit
 */
export interface GithubCommit {
    /**
     * 
     * @type {any}
     * @memberof GithubCommit
     */
    'id': any;
    /**
     * 
     * @type {any}
     * @memberof GithubCommit
     */
    'url': any;
    /**
     * 
     * @type {any}
     * @memberof GithubCommit
     */
    'message': any;
    /**
     * 
     * @type {GithubAuthor}
     * @memberof GithubCommit
     */
    'author': GithubAuthor;
}

