/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GithubUser } from "./github-user";
// May contain unused imports in some cases
// @ts-ignore
import { GithubWebhookCheckRun } from "./github-webhook-check-run";
// May contain unused imports in some cases
// @ts-ignore
import { GithubWebhookCheckSuite } from "./github-webhook-check-suite";
// May contain unused imports in some cases
// @ts-ignore
import { GithubWebhookComment } from "./github-webhook-comment";
// May contain unused imports in some cases
// @ts-ignore
import { GithubWebhookDiscussion } from "./github-webhook-discussion";
// May contain unused imports in some cases
// @ts-ignore
import { GithubWebhookHeadCommit } from "./github-webhook-head-commit";
// May contain unused imports in some cases
// @ts-ignore
import { GithubWebhookIssue } from "./github-webhook-issue";
// May contain unused imports in some cases
// @ts-ignore
import { GithubWebhookMember } from "./github-webhook-member";
// May contain unused imports in some cases
// @ts-ignore
import { GithubWebhookRelease } from "./github-webhook-release";
// May contain unused imports in some cases
// @ts-ignore
import { GithubWebhookRepository } from "./github-webhook-repository";
// May contain unused imports in some cases
// @ts-ignore
import { GithubWebhookReview } from "./github-webhook-review";

/**
 *
 * @export
 * @interface GithubWebhook
 */
export interface GithubWebhook {
  /**
   *
   * @type {any}
   * @memberof GithubWebhook
   */
  action?: any;
  /**
   *
   * @type {any}
   * @memberof GithubWebhook
   */
  ref?: any;
  /**
   *
   * @type {any}
   * @memberof GithubWebhook
   */
  ref_type?: any;
  /**
   *
   * @type {GithubWebhookComment}
   * @memberof GithubWebhook
   */
  comment?: GithubWebhookComment;
  /**
   *
   * @type {GithubWebhookIssue}
   * @memberof GithubWebhook
   */
  issue?: GithubWebhookIssue;
  /**
   *
   * @type {GithubWebhookIssue}
   * @memberof GithubWebhook
   */
  pull_request?: GithubWebhookIssue;
  /**
   *
   * @type {GithubWebhookRepository}
   * @memberof GithubWebhook
   */
  repository?: GithubWebhookRepository;
  /**
   *
   * @type {GithubWebhookRepository}
   * @memberof GithubWebhook
   */
  forkee?: GithubWebhookRepository;
  /**
   *
   * @type {GithubUser}
   * @memberof GithubWebhook
   */
  sender: GithubUser;
  /**
   *
   * @type {GithubWebhookMember}
   * @memberof GithubWebhook
   */
  member?: GithubWebhookMember;
  /**
   *
   * @type {GithubWebhookRelease}
   * @memberof GithubWebhook
   */
  release?: GithubWebhookRelease;
  /**
   *
   * @type {GithubWebhookHeadCommit}
   * @memberof GithubWebhook
   */
  head_commit?: GithubWebhookHeadCommit;
  /**
   *
   * @type {any}
   * @memberof GithubWebhook
   */
  commits?: any;
  /**
   *
   * @type {any}
   * @memberof GithubWebhook
   */
  forced?: any;
  /**
   *
   * @type {any}
   * @memberof GithubWebhook
   */
  compare?: any;
  /**
   *
   * @type {GithubWebhookReview}
   * @memberof GithubWebhook
   */
  review?: GithubWebhookReview;
  /**
   *
   * @type {GithubWebhookCheckRun}
   * @memberof GithubWebhook
   */
  check_run?: GithubWebhookCheckRun;
  /**
   *
   * @type {GithubWebhookCheckSuite}
   * @memberof GithubWebhook
   */
  check_suite?: GithubWebhookCheckSuite;
  /**
   *
   * @type {GithubWebhookDiscussion}
   * @memberof GithubWebhook
   */
  discussion?: GithubWebhookDiscussion;
  /**
   *
   * @type {GithubWebhookComment}
   * @memberof GithubWebhook
   */
  answer?: GithubWebhookComment;
}
