/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GithubCheckRunOutput } from './github-check-run-output';
// May contain unused imports in some cases
// @ts-ignore
import { GithubCheckSuite } from './github-check-suite';

/**
 * 
 * @export
 * @interface GithubCheckRun
 */
export interface GithubCheckRun {
    /**
     * 
     * @type {any}
     * @memberof GithubCheckRun
     */
    'conclusion'?: any;
    /**
     * 
     * @type {any}
     * @memberof GithubCheckRun
     */
    'name': any;
    /**
     * 
     * @type {any}
     * @memberof GithubCheckRun
     */
    'html_url': any;
    /**
     * 
     * @type {GithubCheckSuite}
     * @memberof GithubCheckRun
     */
    'check_suite': GithubCheckSuite;
    /**
     * 
     * @type {any}
     * @memberof GithubCheckRun
     */
    'details_url'?: any;
    /**
     * 
     * @type {GithubCheckRunOutput}
     * @memberof GithubCheckRun
     */
    'output'?: GithubCheckRunOutput;
    /**
     * 
     * @type {any}
     * @memberof GithubCheckRun
     */
    'pull_requests'?: any;
}

