/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GuildRoleResponseTags } from "./guild-role-response-tags";

/**
 *
 * @export
 * @interface GuildRoleResponse
 */
export interface GuildRoleResponse {
  /**
   *
   * @type {any}
   * @memberof GuildRoleResponse
   */
  id: any;
  /**
   *
   * @type {any}
   * @memberof GuildRoleResponse
   */
  name: any;
  /**
   *
   * @type {any}
   * @memberof GuildRoleResponse
   */
  description?: any;
  /**
   *
   * @type {any}
   * @memberof GuildRoleResponse
   */
  permissions: any;
  /**
   *
   * @type {any}
   * @memberof GuildRoleResponse
   */
  position: any;
  /**
   *
   * @type {any}
   * @memberof GuildRoleResponse
   */
  color: any;
  /**
   *
   * @type {any}
   * @memberof GuildRoleResponse
   */
  hoist: any;
  /**
   *
   * @type {any}
   * @memberof GuildRoleResponse
   */
  managed: any;
  /**
   *
   * @type {any}
   * @memberof GuildRoleResponse
   */
  mentionable: any;
  /**
   *
   * @type {any}
   * @memberof GuildRoleResponse
   */
  icon?: any;
  /**
   *
   * @type {any}
   * @memberof GuildRoleResponse
   */
  unicode_emoji?: any;
  /**
   *
   * @type {GuildRoleResponseTags}
   * @memberof GuildRoleResponse
   */
  tags?: GuildRoleResponseTags;
}
