/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ApplicationOAuth2ParamsResponse } from './application-oauth2-params-response';
// May contain unused imports in some cases
// @ts-ignore
import { ApplicationTypes } from './application-types';
// May contain unused imports in some cases
// @ts-ignore
import { InviteApplicationResponse } from './invite-application-response';
// May contain unused imports in some cases
// @ts-ignore
import { UpdateSelfVoiceStateRequestChannelId } from './update-self-voice-state-request-channel-id';
// May contain unused imports in some cases
// @ts-ignore
import { UserResponse } from './user-response';

/**
 * @type GuildInviteResponseTargetApplication
 * @export
 */
export type GuildInviteResponseTargetApplication = InviteApplicationResponse | any;


