/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GuildHomeSettingsResponseWelcomeMessage } from "./guild-home-settings-response-welcome-message";

/**
 *
 * @export
 * @interface GuildHomeSettingsResponse
 */
export interface GuildHomeSettingsResponse {
  /**
   *
   * @type {any}
   * @memberof GuildHomeSettingsResponse
   */
  guild_id: any;
  /**
   *
   * @type {any}
   * @memberof GuildHomeSettingsResponse
   */
  enabled: any;
  /**
   *
   * @type {GuildHomeSettingsResponseWelcomeMessage}
   * @memberof GuildHomeSettingsResponse
   */
  welcome_message?: GuildHomeSettingsResponseWelcomeMessage;
  /**
   *
   * @type {any}
   * @memberof GuildHomeSettingsResponse
   */
  new_member_actions?: any;
  /**
   *
   * @type {any}
   * @memberof GuildHomeSettingsResponse
   */
  resource_channels?: any;
}
