/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GuildTemplateRoleResponse
 */
export interface GuildTemplateRoleResponse {
    /**
     *
     * @type {any}
     * @memberof GuildTemplateRoleResponse
     */
    id: any;
    /**
     *
     * @type {any}
     * @memberof GuildTemplateRoleResponse
     */
    name: any;
    /**
     *
     * @type {any}
     * @memberof GuildTemplateRoleResponse
     */
    permissions: any;
    /**
     *
     * @type {any}
     * @memberof GuildTemplateRoleResponse
     */
    color: any;
    /**
     *
     * @type {any}
     * @memberof GuildTemplateRoleResponse
     */
    hoist: any;
    /**
     *
     * @type {any}
     * @memberof GuildTemplateRoleResponse
     */
    mentionable: any;
    /**
     *
     * @type {any}
     * @memberof GuildTemplateRoleResponse
     */
    icon?: any;
    /**
     *
     * @type {any}
     * @memberof GuildTemplateRoleResponse
     */
    unicode_emoji?: any;
}
