/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GuildPreviewResponse
 */
export interface GuildPreviewResponse {
  /**
   *
   * @type {any}
   * @memberof GuildPreviewResponse
   */
  id: any;
  /**
   *
   * @type {any}
   * @memberof GuildPreviewResponse
   */
  name: any;
  /**
   *
   * @type {any}
   * @memberof GuildPreviewResponse
   */
  icon?: any;
  /**
   *
   * @type {any}
   * @memberof GuildPreviewResponse
   */
  description?: any;
  /**
   *
   * @type {any}
   * @memberof GuildPreviewResponse
   */
  home_header?: any;
  /**
   *
   * @type {any}
   * @memberof GuildPreviewResponse
   */
  splash?: any;
  /**
   *
   * @type {any}
   * @memberof GuildPreviewResponse
   */
  discovery_splash?: any;
  /**
   *
   * @type {any}
   * @memberof GuildPreviewResponse
   */
  features: any;
  /**
   *
   * @type {any}
   * @memberof GuildPreviewResponse
   */
  approximate_member_count: any;
  /**
   *
   * @type {any}
   * @memberof GuildPreviewResponse
   */
  approximate_presence_count: any;
  /**
   *
   * @type {any}
   * @memberof GuildPreviewResponse
   */
  emojis: any;
  /**
   *
   * @type {any}
   * @memberof GuildPreviewResponse
   */
  stickers: any;
}
