/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseApplicationId } from './basic-message-response-application-id';
// May contain unused imports in some cases
// @ts-ignore
import { ChannelFollowerWebhookResponseUser } from './channel-follower-webhook-response-user';
// May contain unused imports in some cases
// @ts-ignore
import { WebhookTypes } from './webhook-types';

/**
 * 
 * @export
 * @interface GuildIncomingWebhookResponse
 */
export interface GuildIncomingWebhookResponse {
    /**
     * 
     * @type {BasicMessageResponseApplicationId}
     * @memberof GuildIncomingWebhookResponse
     */
    'application_id'?: BasicMessageResponseApplicationId;
    /**
     * 
     * @type {any}
     * @memberof GuildIncomingWebhookResponse
     */
    'avatar'?: any;
    /**
     * 
     * @type {BasicMessageResponseApplicationId}
     * @memberof GuildIncomingWebhookResponse
     */
    'channel_id'?: BasicMessageResponseApplicationId;
    /**
     * 
     * @type {BasicMessageResponseApplicationId}
     * @memberof GuildIncomingWebhookResponse
     */
    'guild_id'?: BasicMessageResponseApplicationId;
    /**
     * 
     * @type {any}
     * @memberof GuildIncomingWebhookResponse
     */
    'id': any;
    /**
     * 
     * @type {any}
     * @memberof GuildIncomingWebhookResponse
     */
    'name': any;
    /**
     * 
     * @type {WebhookTypes}
     * @memberof GuildIncomingWebhookResponse
     */
    'type': WebhookTypes;
    /**
     * 
     * @type {ChannelFollowerWebhookResponseUser}
     * @memberof GuildIncomingWebhookResponse
     */
    'user'?: ChannelFollowerWebhookResponseUser;
    /**
     * 
     * @type {any}
     * @memberof GuildIncomingWebhookResponse
     */
    'token'?: any;
    /**
     * 
     * @type {any}
     * @memberof GuildIncomingWebhookResponse
     */
    'url'?: any;
}

