/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ChannelFollowerWebhookResponseUser } from "./channel-follower-webhook-response-user";
// May contain unused imports in some cases
// @ts-ignore
import { GuildTemplateSnapshotResponse } from "./guild-template-snapshot-response";

/**
 *
 * @export
 * @interface GuildTemplateResponse
 */
export interface GuildTemplateResponse {
  /**
   *
   * @type {any}
   * @memberof GuildTemplateResponse
   */
  code: any;
  /**
   *
   * @type {any}
   * @memberof GuildTemplateResponse
   */
  name: any;
  /**
   *
   * @type {any}
   * @memberof GuildTemplateResponse
   */
  description?: any;
  /**
   *
   * @type {any}
   * @memberof GuildTemplateResponse
   */
  usage_count: any;
  /**
   *
   * @type {any}
   * @memberof GuildTemplateResponse
   */
  creator_id: any;
  /**
   *
   * @type {ChannelFollowerWebhookResponseUser}
   * @memberof GuildTemplateResponse
   */
  creator?: ChannelFollowerWebhookResponseUser;
  /**
   *
   * @type {any}
   * @memberof GuildTemplateResponse
   */
  created_at: any;
  /**
   *
   * @type {any}
   * @memberof GuildTemplateResponse
   */
  updated_at: any;
  /**
   *
   * @type {any}
   * @memberof GuildTemplateResponse
   */
  source_guild_id: any;
  /**
   *
   * @type {GuildTemplateSnapshotResponse}
   * @memberof GuildTemplateResponse
   */
  serialized_source_guild: GuildTemplateSnapshotResponse;
  /**
   *
   * @type {any}
   * @memberof GuildTemplateResponse
   */
  is_dirty?: any;
}
