/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseApplicationId } from "./basic-message-response-application-id";
// May contain unused imports in some cases
// @ts-ignore
import { ChannelTypes } from "./channel-types";
// May contain unused imports in some cases
// @ts-ignore
import { CreateForumThreadRequestAutoArchiveDuration } from "./create-forum-thread-request-auto-archive-duration";
// May contain unused imports in some cases
// @ts-ignore
import { CreateGuildChannelRequestDefaultForumLayout } from "./create-guild-channel-request-default-forum-layout";
// May contain unused imports in some cases
// @ts-ignore
import { CreateGuildChannelRequestDefaultSortOrder } from "./create-guild-channel-request-default-sort-order";
// May contain unused imports in some cases
// @ts-ignore
import { GuildChannelResponseDefaultReactionEmoji } from "./guild-channel-response-default-reaction-emoji";
// May contain unused imports in some cases
// @ts-ignore
import { GuildTemplateChannelResponseIconEmoji } from "./guild-template-channel-response-icon-emoji";

/**
 *
 * @export
 * @interface GuildTemplateChannelResponse
 */
export interface GuildTemplateChannelResponse {
    /**
     *
     * @type {any}
     * @memberof GuildTemplateChannelResponse
     */
    id?: any;
    /**
     *
     * @type {ChannelTypes}
     * @memberof GuildTemplateChannelResponse
     */
    type: ChannelTypes;
    /**
     *
     * @type {any}
     * @memberof GuildTemplateChannelResponse
     */
    name?: any;
    /**
     *
     * @type {any}
     * @memberof GuildTemplateChannelResponse
     */
    position?: any;
    /**
     *
     * @type {any}
     * @memberof GuildTemplateChannelResponse
     */
    topic?: any;
    /**
     *
     * @type {any}
     * @memberof GuildTemplateChannelResponse
     */
    bitrate: any;
    /**
     *
     * @type {any}
     * @memberof GuildTemplateChannelResponse
     */
    user_limit: any;
    /**
     *
     * @type {any}
     * @memberof GuildTemplateChannelResponse
     */
    nsfw: any;
    /**
     *
     * @type {any}
     * @memberof GuildTemplateChannelResponse
     */
    rate_limit_per_user: any;
    /**
     *
     * @type {BasicMessageResponseApplicationId}
     * @memberof GuildTemplateChannelResponse
     */
    parent_id?: BasicMessageResponseApplicationId;
    /**
     *
     * @type {CreateForumThreadRequestAutoArchiveDuration}
     * @memberof GuildTemplateChannelResponse
     */
    default_auto_archive_duration?: CreateForumThreadRequestAutoArchiveDuration;
    /**
     *
     * @type {any}
     * @memberof GuildTemplateChannelResponse
     */
    permission_overwrites: any;
    /**
     *
     * @type {any}
     * @memberof GuildTemplateChannelResponse
     */
    available_tags?: any;
    /**
     *
     * @type {any}
     * @memberof GuildTemplateChannelResponse
     */
    template: any;
    /**
     *
     * @type {GuildChannelResponseDefaultReactionEmoji}
     * @memberof GuildTemplateChannelResponse
     */
    default_reaction_emoji?: GuildChannelResponseDefaultReactionEmoji;
    /**
     *
     * @type {any}
     * @memberof GuildTemplateChannelResponse
     */
    default_thread_rate_limit_per_user?: any;
    /**
     *
     * @type {CreateGuildChannelRequestDefaultSortOrder}
     * @memberof GuildTemplateChannelResponse
     */
    default_sort_order?: CreateGuildChannelRequestDefaultSortOrder;
    /**
     *
     * @type {CreateGuildChannelRequestDefaultForumLayout}
     * @memberof GuildTemplateChannelResponse
     */
    default_forum_layout?: CreateGuildChannelRequestDefaultForumLayout;
    /**
     *
     * @type {GuildTemplateChannelResponseIconEmoji}
     * @memberof GuildTemplateChannelResponse
     */
    icon_emoji?: GuildTemplateChannelResponseIconEmoji;
    /**
     *
     * @type {any}
     * @memberof GuildTemplateChannelResponse
     */
    theme_color?: any;
}
