/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseApplicationId } from "./basic-message-response-application-id";
// May contain unused imports in some cases
// @ts-ignore
import { ChannelFollowerWebhookResponseUser } from "./channel-follower-webhook-response-user";
// May contain unused imports in some cases
// @ts-ignore
import { FriendInviteResponseChannel } from "./friend-invite-response-channel";
// May contain unused imports in some cases
// @ts-ignore
import { GuildInviteResponseGuild } from "./guild-invite-response-guild";
// May contain unused imports in some cases
// @ts-ignore
import { GuildInviteResponseGuildScheduledEvent } from "./guild-invite-response-guild-scheduled-event";
// May contain unused imports in some cases
// @ts-ignore
import { GuildInviteResponseStageInstance } from "./guild-invite-response-stage-instance";
// May contain unused imports in some cases
// @ts-ignore
import { GuildInviteResponseTargetApplication } from "./guild-invite-response-target-application";
// May contain unused imports in some cases
// @ts-ignore
import { GuildInviteResponseTargetType } from "./guild-invite-response-target-type";
// May contain unused imports in some cases
// @ts-ignore
import { GuildInviteResponseType } from "./guild-invite-response-type";

/**
 *
 * @export
 * @interface GuildInviteResponse
 */
export interface GuildInviteResponse {
  /**
   *
   * @type {GuildInviteResponseType}
   * @memberof GuildInviteResponse
   */
  type?: GuildInviteResponseType;
  /**
   *
   * @type {any}
   * @memberof GuildInviteResponse
   */
  code: any;
  /**
   *
   * @type {ChannelFollowerWebhookResponseUser}
   * @memberof GuildInviteResponse
   */
  inviter?: ChannelFollowerWebhookResponseUser;
  /**
   *
   * @type {any}
   * @memberof GuildInviteResponse
   */
  max_age?: any;
  /**
   *
   * @type {any}
   * @memberof GuildInviteResponse
   */
  created_at?: any;
  /**
   *
   * @type {any}
   * @memberof GuildInviteResponse
   */
  expires_at?: any;
  /**
   *
   * @type {any}
   * @memberof GuildInviteResponse
   */
  is_contact?: any;
  /**
   *
   * @type {any}
   * @memberof GuildInviteResponse
   */
  flags?: any;
  /**
   *
   * @type {GuildInviteResponseGuild}
   * @memberof GuildInviteResponse
   */
  guild?: GuildInviteResponseGuild;
  /**
   *
   * @type {BasicMessageResponseApplicationId}
   * @memberof GuildInviteResponse
   */
  guild_id?: BasicMessageResponseApplicationId;
  /**
   *
   * @type {FriendInviteResponseChannel}
   * @memberof GuildInviteResponse
   */
  channel?: FriendInviteResponseChannel;
  /**
   *
   * @type {GuildInviteResponseStageInstance}
   * @memberof GuildInviteResponse
   */
  stage_instance?: GuildInviteResponseStageInstance;
  /**
   *
   * @type {GuildInviteResponseTargetType}
   * @memberof GuildInviteResponse
   */
  target_type?: GuildInviteResponseTargetType;
  /**
   *
   * @type {ChannelFollowerWebhookResponseUser}
   * @memberof GuildInviteResponse
   */
  target_user?: ChannelFollowerWebhookResponseUser;
  /**
   *
   * @type {GuildInviteResponseTargetApplication}
   * @memberof GuildInviteResponse
   */
  target_application?: GuildInviteResponseTargetApplication;
  /**
   *
   * @type {GuildInviteResponseGuildScheduledEvent}
   * @memberof GuildInviteResponse
   */
  guild_scheduled_event?: GuildInviteResponseGuildScheduledEvent;
  /**
   *
   * @type {any}
   * @memberof GuildInviteResponse
   */
  uses?: any;
  /**
   *
   * @type {any}
   * @memberof GuildInviteResponse
   */
  max_uses?: any;
  /**
   *
   * @type {any}
   * @memberof GuildInviteResponse
   */
  temporary?: any;
  /**
   *
   * @type {any}
   * @memberof GuildInviteResponse
   */
  approximate_member_count?: any;
  /**
   *
   * @type {any}
   * @memberof GuildInviteResponse
   */
  approximate_presence_count?: any;
}
