/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GuildOnboardingResponse
 */
export interface GuildOnboardingResponse {
    /**
     *
     * @type {any}
     * @memberof GuildOnboardingResponse
     */
    guild_id: any;
    /**
     *
     * @type {any}
     * @memberof GuildOnboardingResponse
     */
    prompts: any;
    /**
     *
     * @type {any}
     * @memberof GuildOnboardingResponse
     */
    default_channel_ids: any;
    /**
     *
     * @type {boolean}
     * @memberof GuildOnboardingResponse
     */
    enabled: boolean;
}
