/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { BaseCreateMessageCreateRequestAllowedMentions } from "./base-create-message-create-request-allowed-mentions";

/**
 *
 * @export
 * @interface IncomingWebhookUpdateForInteractionCallbackRequestPartial
 */
export interface IncomingWebhookUpdateForInteractionCallbackRequestPartial {
  /**
   *
   * @type {any}
   * @memberof IncomingWebhookUpdateForInteractionCallbackRequestPartial
   */
  content?: any;
  /**
   *
   * @type {any}
   * @memberof IncomingWebhookUpdateForInteractionCallbackRequestPartial
   */
  embeds?: any;
  /**
   *
   * @type {BaseCreateMessageCreateRequestAllowedMentions}
   * @memberof IncomingWebhookUpdateForInteractionCallbackRequestPartial
   */
  allowed_mentions?: BaseCreateMessageCreateRequestAllowedMentions;
  /**
   *
   * @type {any}
   * @memberof IncomingWebhookUpdateForInteractionCallbackRequestPartial
   */
  components?: any;
  /**
   *
   * @type {any}
   * @memberof IncomingWebhookUpdateForInteractionCallbackRequestPartial
   */
  attachments?: any;
  /**
   *
   * @type {number}
   * @memberof IncomingWebhookUpdateForInteractionCallbackRequestPartial
   */
  flags?: number | null;
}
