/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BasicApplicationResponseBot } from './basic-application-response-bot';
// May contain unused imports in some cases
// @ts-ignore
import { BasicApplicationResponseType } from './basic-application-response-type';
// May contain unused imports in some cases
// @ts-ignore
import { UpdateSelfVoiceStateRequestChannelId } from './update-self-voice-state-request-channel-id';

/**
 * 
 * @export
 * @interface IntegrationApplicationResponse
 */
export interface IntegrationApplicationResponse {
    /**
     * 
     * @type {any}
     * @memberof IntegrationApplicationResponse
     */
    'id': any;
    /**
     * 
     * @type {string}
     * @memberof IntegrationApplicationResponse
     */
    'name': string | null;
    /**
     * 
     * @type {string}
     * @memberof IntegrationApplicationResponse
     */
    'icon'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IntegrationApplicationResponse
     */
    'description': string | null;
    /**
     * 
     * @type {BasicApplicationResponseType}
     * @memberof IntegrationApplicationResponse
     */
    'type'?: BasicApplicationResponseType | null;
    /**
     * 
     * @type {string}
     * @memberof IntegrationApplicationResponse
     */
    'cover_image'?: string | null;
    /**
     * 
     * @type {UpdateSelfVoiceStateRequestChannelId}
     * @memberof IntegrationApplicationResponse
     */
    'primary_sku_id'?: UpdateSelfVoiceStateRequestChannelId | null;
    /**
     * 
     * @type {BasicApplicationResponseBot}
     * @memberof IntegrationApplicationResponse
     */
    'bot'?: BasicApplicationResponseBot | null;
}

