/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GuildCreateRequestVerificationLevel } from "./guild-create-request-verification-level";
// May contain unused imports in some cases
// @ts-ignore
import { InviteGuildResponseNsfwLevel } from "./invite-guild-response-nsfw-level";

/**
 *
 * @export
 * @interface InviteGuildResponse
 */
export interface InviteGuildResponse {
  /**
   *
   * @type {any}
   * @memberof InviteGuildResponse
   */
  id: any;
  /**
   *
   * @type {any}
   * @memberof InviteGuildResponse
   */
  name: any;
  /**
   *
   * @type {any}
   * @memberof InviteGuildResponse
   */
  splash?: any;
  /**
   *
   * @type {any}
   * @memberof InviteGuildResponse
   */
  banner?: any;
  /**
   *
   * @type {any}
   * @memberof InviteGuildResponse
   */
  description?: any;
  /**
   *
   * @type {any}
   * @memberof InviteGuildResponse
   */
  icon?: any;
  /**
   *
   * @type {any}
   * @memberof InviteGuildResponse
   */
  features: any;
  /**
   *
   * @type {GuildCreateRequestVerificationLevel}
   * @memberof InviteGuildResponse
   */
  verification_level?: GuildCreateRequestVerificationLevel;
  /**
   *
   * @type {any}
   * @memberof InviteGuildResponse
   */
  vanity_url_code?: any;
  /**
   *
   * @type {InviteGuildResponseNsfwLevel}
   * @memberof InviteGuildResponse
   */
  nsfw_level?: InviteGuildResponseNsfwLevel;
  /**
   *
   * @type {any}
   * @memberof InviteGuildResponse
   */
  nsfw?: any;
  /**
   *
   * @type {any}
   * @memberof InviteGuildResponse
   */
  premium_subscription_count?: any;
}
