/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AutomodEventType } from './automod-event-type';
// May contain unused imports in some cases
// @ts-ignore
import { AutomodTriggerType } from './automod-trigger-type';
// May contain unused imports in some cases
// @ts-ignore
import { MentionSpamTriggerMetadataResponse } from './mention-spam-trigger-metadata-response';

/**
 * 
 * @export
 * @interface MentionSpamRuleResponse
 */
export interface MentionSpamRuleResponse {
    /**
     * 
     * @type {any}
     * @memberof MentionSpamRuleResponse
     */
    'id': any;
    /**
     * 
     * @type {any}
     * @memberof MentionSpamRuleResponse
     */
    'guild_id': any;
    /**
     * 
     * @type {any}
     * @memberof MentionSpamRuleResponse
     */
    'creator_id': any;
    /**
     * 
     * @type {any}
     * @memberof MentionSpamRuleResponse
     */
    'name': any;
    /**
     * 
     * @type {AutomodEventType}
     * @memberof MentionSpamRuleResponse
     */
    'event_type': AutomodEventType;
    /**
     * 
     * @type {any}
     * @memberof MentionSpamRuleResponse
     */
    'actions': any;
    /**
     * 
     * @type {AutomodTriggerType}
     * @memberof MentionSpamRuleResponse
     */
    'trigger_type': AutomodTriggerType;
    /**
     * 
     * @type {any}
     * @memberof MentionSpamRuleResponse
     */
    'enabled'?: any;
    /**
     * 
     * @type {any}
     * @memberof MentionSpamRuleResponse
     */
    'exempt_roles'?: any;
    /**
     * 
     * @type {any}
     * @memberof MentionSpamRuleResponse
     */
    'exempt_channels'?: any;
    /**
     * 
     * @type {MentionSpamTriggerMetadataResponse}
     * @memberof MentionSpamRuleResponse
     */
    'trigger_metadata': MentionSpamTriggerMetadataResponse;
}

