/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { BaseCreateMessageCreateRequestAllowedMentions } from "./base-create-message-create-request-allowed-mentions";
// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseNonce } from "./basic-message-response-nonce";
// May contain unused imports in some cases
// @ts-ignore
import { MessageCreateRequestMessageReference } from "./message-create-request-message-reference";

/**
 *
 * @export
 * @interface MessageCreateRequest
 */
export interface MessageCreateRequest {
  /**
   *
   * @type {any}
   * @memberof MessageCreateRequest
   */
  content?: any;
  /**
   *
   * @type {any}
   * @memberof MessageCreateRequest
   */
  embeds?: any;
  /**
   *
   * @type {BaseCreateMessageCreateRequestAllowedMentions}
   * @memberof MessageCreateRequest
   */
  allowed_mentions?: BaseCreateMessageCreateRequestAllowedMentions;
  /**
   *
   * @type {any}
   * @memberof MessageCreateRequest
   */
  sticker_ids?: any;
  /**
   *
   * @type {any}
   * @memberof MessageCreateRequest
   */
  components?: any;
  /**
   *
   * @type {any}
   * @memberof MessageCreateRequest
   */
  flags?: any;
  /**
   *
   * @type {any}
   * @memberof MessageCreateRequest
   */
  attachments?: any;
  /**
   *
   * @type {MessageCreateRequestMessageReference}
   * @memberof MessageCreateRequest
   */
  message_reference?: MessageCreateRequestMessageReference;
  /**
   *
   * @type {BasicMessageResponseNonce}
   * @memberof MessageCreateRequest
   */
  nonce?: BasicMessageResponseNonce;
  /**
   *
   * @type {any}
   * @memberof MessageCreateRequest
   */
  tts?: any;
}
