/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { MessageComponentTypes } from "./message-component-types";

/**
 *
 * @export
 * @interface MessageComponentStringSelectResponse
 */
export interface MessageComponentStringSelectResponse {
    /**
     *
     * @type {MessageComponentTypes}
     * @memberof MessageComponentStringSelectResponse
     */
    type: MessageComponentTypes;
    /**
     *
     * @type {any}
     * @memberof MessageComponentStringSelectResponse
     */
    custom_id: any;
    /**
     *
     * @type {any}
     * @memberof MessageComponentStringSelectResponse
     */
    placeholder?: any;
    /**
     *
     * @type {any}
     * @memberof MessageComponentStringSelectResponse
     */
    min_values?: any;
    /**
     *
     * @type {any}
     * @memberof MessageComponentStringSelectResponse
     */
    max_values?: any;
    /**
     *
     * @type {any}
     * @memberof MessageComponentStringSelectResponse
     */
    disabled?: any;
    /**
     *
     * @type {any}
     * @memberof MessageComponentStringSelectResponse
     */
    options?: any;
}
