/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MessageRoleSubscriptionDataResponse
 */
export interface MessageRoleSubscriptionDataResponse {
    /**
     * 
     * @type {any}
     * @memberof MessageRoleSubscriptionDataResponse
     */
    'role_subscription_listing_id': any;
    /**
     * 
     * @type {any}
     * @memberof MessageRoleSubscriptionDataResponse
     */
    'tier_name': any;
    /**
     * 
     * @type {any}
     * @memberof MessageRoleSubscriptionDataResponse
     */
    'total_months_subscribed': any;
    /**
     * 
     * @type {any}
     * @memberof MessageRoleSubscriptionDataResponse
     */
    'is_renewal': any;
}

