/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ChannelTypes } from "./channel-types";

/**
 *
 * @export
 * @interface MessageMentionChannelResponse
 */
export interface MessageMentionChannelResponse {
    /**
     *
     * @type {any}
     * @memberof MessageMentionChannelResponse
     */
    id: any;
    /**
     *
     * @type {any}
     * @memberof MessageMentionChannelResponse
     */
    name: any;
    /**
     *
     * @type {ChannelTypes}
     * @memberof MessageMentionChannelResponse
     */
    type: ChannelTypes;
    /**
     *
     * @type {any}
     * @memberof MessageMentionChannelResponse
     */
    guild_id: any;
}
