/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MessageAllowedMentionsRequest
 */
export interface MessageAllowedMentionsRequest {
  /**
   *
   * @type {any}
   * @memberof MessageAllowedMentionsRequest
   */
  parse?: any;
  /**
   *
   * @type {any}
   * @memberof MessageAllowedMentionsRequest
   */
  users?: any;
  /**
   *
   * @type {any}
   * @memberof MessageAllowedMentionsRequest
   */
  roles?: any;
  /**
   *
   * @type {any}
   * @memberof MessageAllowedMentionsRequest
   */
  replied_user?: any;
}
