/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ChannelFollowerWebhookResponseUser } from "./channel-follower-webhook-response-user";
// May contain unused imports in some cases
// @ts-ignore
import { InteractionTypes } from "./interaction-types";

/**
 *
 * @export
 * @interface MessageInteractionResponse
 */
export interface MessageInteractionResponse {
    /**
     *
     * @type {any}
     * @memberof MessageInteractionResponse
     */
    id: any;
    /**
     *
     * @type {InteractionTypes}
     * @memberof MessageInteractionResponse
     */
    type: InteractionTypes;
    /**
     *
     * @type {any}
     * @memberof MessageInteractionResponse
     */
    name: any;
    /**
     *
     * @type {ChannelFollowerWebhookResponseUser}
     * @memberof MessageInteractionResponse
     */
    user?: ChannelFollowerWebhookResponseUser;
    /**
     *
     * @type {any}
     * @memberof MessageInteractionResponse
     */
    name_localized?: any;
}
