/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MessageEmbedAuthorResponse
 */
export interface MessageEmbedAuthorResponse {
  /**
   *
   * @type {any}
   * @memberof MessageEmbedAuthorResponse
   */
  name: any;
  /**
   *
   * @type {any}
   * @memberof MessageEmbedAuthorResponse
   */
  url?: any;
  /**
   *
   * @type {any}
   * @memberof MessageEmbedAuthorResponse
   */
  icon_url?: any;
  /**
   *
   * @type {any}
   * @memberof MessageEmbedAuthorResponse
   */
  proxy_icon_url?: any;
}
