/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MessageEmbedFooterResponse
 */
export interface MessageEmbedFooterResponse {
  /**
   *
   * @type {any}
   * @memberof MessageEmbedFooterResponse
   */
  text: any;
  /**
   *
   * @type {any}
   * @memberof MessageEmbedFooterResponse
   */
  icon_url?: any;
  /**
   *
   * @type {any}
   * @memberof MessageEmbedFooterResponse
   */
  proxy_icon_url?: any;
}
