/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { MessageReactionCountDetailsResponse } from "./message-reaction-count-details-response";
// May contain unused imports in some cases
// @ts-ignore
import { MessageReactionEmojiResponse } from "./message-reaction-emoji-response";

/**
 *
 * @export
 * @interface MessageReactionResponse
 */
export interface MessageReactionResponse {
  /**
   *
   * @type {MessageReactionEmojiResponse}
   * @memberof MessageReactionResponse
   */
  emoji: MessageReactionEmojiResponse;
  /**
   *
   * @type {any}
   * @memberof MessageReactionResponse
   */
  count: any;
  /**
   *
   * @type {MessageReactionCountDetailsResponse}
   * @memberof MessageReactionResponse
   */
  count_details: MessageReactionCountDetailsResponse;
  /**
   *
   * @type {any}
   * @memberof MessageReactionResponse
   */
  burst_colors: any;
  /**
   *
   * @type {any}
   * @memberof MessageReactionResponse
   */
  me_burst: any;
  /**
   *
   * @type {any}
   * @memberof MessageReactionResponse
   */
  me: any;
}
