/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MessageEmbedResponseAuthor } from './message-embed-response-author';
// May contain unused imports in some cases
// @ts-ignore
import { MessageEmbedResponseFooter } from './message-embed-response-footer';
// May contain unused imports in some cases
// @ts-ignore
import { MessageEmbedResponseImage } from './message-embed-response-image';
// May contain unused imports in some cases
// @ts-ignore
import { MessageEmbedResponseProvider } from './message-embed-response-provider';
// May contain unused imports in some cases
// @ts-ignore
import { MessageEmbedResponseVideo } from './message-embed-response-video';

/**
 * 
 * @export
 * @interface MessageEmbedResponse
 */
export interface MessageEmbedResponse {
    /**
     * 
     * @type {any}
     * @memberof MessageEmbedResponse
     */
    'type': any;
    /**
     * 
     * @type {any}
     * @memberof MessageEmbedResponse
     */
    'url'?: any;
    /**
     * 
     * @type {any}
     * @memberof MessageEmbedResponse
     */
    'title'?: any;
    /**
     * 
     * @type {any}
     * @memberof MessageEmbedResponse
     */
    'description'?: any;
    /**
     * 
     * @type {any}
     * @memberof MessageEmbedResponse
     */
    'color'?: any;
    /**
     * 
     * @type {any}
     * @memberof MessageEmbedResponse
     */
    'timestamp'?: any;
    /**
     * 
     * @type {any}
     * @memberof MessageEmbedResponse
     */
    'fields'?: any;
    /**
     * 
     * @type {MessageEmbedResponseAuthor}
     * @memberof MessageEmbedResponse
     */
    'author'?: MessageEmbedResponseAuthor;
    /**
     * 
     * @type {MessageEmbedResponseProvider}
     * @memberof MessageEmbedResponse
     */
    'provider'?: MessageEmbedResponseProvider;
    /**
     * 
     * @type {MessageEmbedResponseImage}
     * @memberof MessageEmbedResponse
     */
    'image'?: MessageEmbedResponseImage;
    /**
     * 
     * @type {MessageEmbedResponseImage}
     * @memberof MessageEmbedResponse
     */
    'thumbnail'?: MessageEmbedResponseImage;
    /**
     * 
     * @type {MessageEmbedResponseVideo}
     * @memberof MessageEmbedResponse
     */
    'video'?: MessageEmbedResponseVideo;
    /**
     * 
     * @type {MessageEmbedResponseFooter}
     * @memberof MessageEmbedResponse
     */
    'footer'?: MessageEmbedResponseFooter;
}

