/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponse } from './basic-message-response';
// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseActivity } from './basic-message-response-activity';
// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseApplication } from './basic-message-response-application';
// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseApplicationId } from './basic-message-response-application-id';
// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseInteraction } from './basic-message-response-interaction';
// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseMessageReference } from './basic-message-response-message-reference';
// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseNonce } from './basic-message-response-nonce';
// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponsePurchaseNotification } from './basic-message-response-purchase-notification';
// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseResolved } from './basic-message-response-resolved';
// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseRoleSubscriptionData } from './basic-message-response-role-subscription-data';
// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseThread } from './basic-message-response-thread';
// May contain unused imports in some cases
// @ts-ignore
import { MessageType } from './message-type';
// May contain unused imports in some cases
// @ts-ignore
import { UserResponse } from './user-response';

/**
 * @type MessageResponseReferencedMessage
 * @export
 */
export type MessageResponseReferencedMessage = BasicMessageResponse | any;


