/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { MessageComponentTypes } from "./message-component-types";
// May contain unused imports in some cases
// @ts-ignore
import { TextStyleTypes } from "./text-style-types";

/**
 *
 * @export
 * @interface MessageComponentInputTextResponse
 */
export interface MessageComponentInputTextResponse {
    /**
     *
     * @type {MessageComponentTypes}
     * @memberof MessageComponentInputTextResponse
     */
    type: MessageComponentTypes;
    /**
     *
     * @type {any}
     * @memberof MessageComponentInputTextResponse
     */
    custom_id: any;
    /**
     *
     * @type {TextStyleTypes}
     * @memberof MessageComponentInputTextResponse
     */
    style: TextStyleTypes;
    /**
     *
     * @type {any}
     * @memberof MessageComponentInputTextResponse
     */
    label?: any;
    /**
     *
     * @type {any}
     * @memberof MessageComponentInputTextResponse
     */
    value?: any;
    /**
     *
     * @type {any}
     * @memberof MessageComponentInputTextResponse
     */
    placeholder?: any;
    /**
     *
     * @type {any}
     * @memberof MessageComponentInputTextResponse
     */
    required?: any;
    /**
     *
     * @type {any}
     * @memberof MessageComponentInputTextResponse
     */
    min_length?: any;
    /**
     *
     * @type {any}
     * @memberof MessageComponentInputTextResponse
     */
    max_length?: any;
}
