/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { MessageEmbedImageResponseWidth } from "./message-embed-image-response-width";

/**
 *
 * @export
 * @interface MessageEmbedImageResponse
 */
export interface MessageEmbedImageResponse {
  /**
   *
   * @type {string}
   * @memberof MessageEmbedImageResponse
   */
  url?: string | null;
  /**
   *
   * @type {string}
   * @memberof MessageEmbedImageResponse
   */
  proxy_url?: string | null;
  /**
   *
   * @type {MessageEmbedImageResponseWidth}
   * @memberof MessageEmbedImageResponse
   */
  width?: MessageEmbedImageResponseWidth;
  /**
   *
   * @type {MessageEmbedImageResponseWidth}
   * @memberof MessageEmbedImageResponse
   */
  height?: MessageEmbedImageResponseWidth;
  /**
   *
   * @type {string}
   * @memberof MessageEmbedImageResponse
   */
  placeholder?: string | null;
  /**
   *
   * @type {MessageEmbedImageResponseWidth}
   * @memberof MessageEmbedImageResponse
   */
  placeholder_version?: MessageEmbedImageResponseWidth;
}
