/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AutomodEventType } from './automod-event-type';
// May contain unused imports in some cases
// @ts-ignore
import { AutomodTriggerType } from './automod-trigger-type';
// May contain unused imports in some cases
// @ts-ignore
import { MLSpamUpsertRequestTriggerMetadata } from './mlspam-upsert-request-trigger-metadata';

/**
 * 
 * @export
 * @interface MLSpamUpsertRequestPartial
 */
export interface MLSpamUpsertRequestPartial {
    /**
     * 
     * @type {any}
     * @memberof MLSpamUpsertRequestPartial
     */
    'name'?: any;
    /**
     * 
     * @type {AutomodEventType}
     * @memberof MLSpamUpsertRequestPartial
     */
    'event_type'?: AutomodEventType;
    /**
     * 
     * @type {any}
     * @memberof MLSpamUpsertRequestPartial
     */
    'actions'?: any;
    /**
     * 
     * @type {any}
     * @memberof MLSpamUpsertRequestPartial
     */
    'enabled'?: any;
    /**
     * 
     * @type {any}
     * @memberof MLSpamUpsertRequestPartial
     */
    'exempt_roles'?: any;
    /**
     * 
     * @type {any}
     * @memberof MLSpamUpsertRequestPartial
     */
    'exempt_channels'?: any;
    /**
     * 
     * @type {AutomodTriggerType}
     * @memberof MLSpamUpsertRequestPartial
     */
    'trigger_type'?: AutomodTriggerType;
    /**
     * 
     * @type {MLSpamUpsertRequestTriggerMetadata}
     * @memberof MLSpamUpsertRequestPartial
     */
    'trigger_metadata'?: MLSpamUpsertRequestTriggerMetadata;
}

