/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { InteractionCallbackTypes } from "./interaction-callback-types";
// May contain unused imports in some cases
// @ts-ignore
import { ModalInteractionCallbackData } from "./modal-interaction-callback-data";

/**
 *
 * @export
 * @interface ModalInteractionCallbackRequest
 */
export interface ModalInteractionCallbackRequest {
  /**
   *
   * @type {InteractionCallbackTypes}
   * @memberof ModalInteractionCallbackRequest
   */
  type: InteractionCallbackTypes;
  /**
   *
   * @type {ModalInteractionCallbackData}
   * @memberof ModalInteractionCallbackRequest
   */
  data: ModalInteractionCallbackData;
}
