/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A single error, either for an API response or a specific field.
 * @export
 * @interface ModelError
 */
export interface ModelError {
  /**
   * Discord internal error code. See error code reference
   * @type {any}
   * @memberof ModelError
   */
  code: any;
  /**
   * Human-readable error message
   * @type {any}
   * @memberof ModelError
   */
  message: any;
}
