/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MyGuildResponse
 */
export interface MyGuildResponse {
    /**
     * 
     * @type {any}
     * @memberof MyGuildResponse
     */
    'id': any;
    /**
     * 
     * @type {any}
     * @memberof MyGuildResponse
     */
    'name': any;
    /**
     * 
     * @type {any}
     * @memberof MyGuildResponse
     */
    'icon'?: any;
    /**
     * 
     * @type {any}
     * @memberof MyGuildResponse
     */
    'owner': any;
    /**
     * 
     * @type {any}
     * @memberof MyGuildResponse
     */
    'permissions': any;
    /**
     * 
     * @type {any}
     * @memberof MyGuildResponse
     */
    'features': any;
    /**
     * 
     * @type {any}
     * @memberof MyGuildResponse
     */
    'approximate_member_count'?: any;
    /**
     * 
     * @type {any}
     * @memberof MyGuildResponse
     */
    'approximate_presence_count'?: any;
}

