/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { NewMemberActionResponseEmoji } from './new-member-action-response-emoji';
// May contain unused imports in some cases
// @ts-ignore
import { NewMemberActionType } from './new-member-action-type';

/**
 * 
 * @export
 * @interface NewMemberActionResponse
 */
export interface NewMemberActionResponse {
    /**
     * 
     * @type {any}
     * @memberof NewMemberActionResponse
     */
    'channel_id': any;
    /**
     * 
     * @type {NewMemberActionType}
     * @memberof NewMemberActionResponse
     */
    'action_type': NewMemberActionType;
    /**
     * 
     * @type {any}
     * @memberof NewMemberActionResponse
     */
    'title': any;
    /**
     * 
     * @type {any}
     * @memberof NewMemberActionResponse
     */
    'description': any;
    /**
     * 
     * @type {NewMemberActionResponseEmoji}
     * @memberof NewMemberActionResponse
     */
    'emoji'?: NewMemberActionResponseEmoji;
    /**
     * 
     * @type {any}
     * @memberof NewMemberActionResponse
     */
    'icon'?: any;
}

