/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseApplicationId } from './basic-message-response-application-id';

/**
 * 
 * @export
 * @interface OnboardingPromptOptionRequest
 */
export interface OnboardingPromptOptionRequest {
    /**
     * 
     * @type {BasicMessageResponseApplicationId}
     * @memberof OnboardingPromptOptionRequest
     */
    'id'?: BasicMessageResponseApplicationId;
    /**
     * 
     * @type {any}
     * @memberof OnboardingPromptOptionRequest
     */
    'title': any;
    /**
     * 
     * @type {any}
     * @memberof OnboardingPromptOptionRequest
     */
    'description'?: any;
    /**
     * 
     * @type {BasicMessageResponseApplicationId}
     * @memberof OnboardingPromptOptionRequest
     */
    'emoji_id'?: BasicMessageResponseApplicationId;
    /**
     * 
     * @type {any}
     * @memberof OnboardingPromptOptionRequest
     */
    'emoji_name'?: any;
    /**
     * 
     * @type {any}
     * @memberof OnboardingPromptOptionRequest
     */
    'emoji_animated'?: any;
    /**
     * 
     * @type {any}
     * @memberof OnboardingPromptOptionRequest
     */
    'role_ids'?: any;
    /**
     * 
     * @type {any}
     * @memberof OnboardingPromptOptionRequest
     */
    'channel_ids'?: any;
}

