/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { DiscordIntegrationResponseAccount } from "./discord-integration-response-account";
// May contain unused imports in some cases
// @ts-ignore
import { IntegrationTypes } from "./integration-types";

/**
 *
 * @export
 * @interface PartialDiscordIntegrationResponse
 */
export interface PartialDiscordIntegrationResponse {
  /**
   *
   * @type {any}
   * @memberof PartialDiscordIntegrationResponse
   */
  id: any;
  /**
   *
   * @type {IntegrationTypes}
   * @memberof PartialDiscordIntegrationResponse
   */
  type: IntegrationTypes;
  /**
   *
   * @type {any}
   * @memberof PartialDiscordIntegrationResponse
   */
  name?: any;
  /**
   *
   * @type {DiscordIntegrationResponseAccount}
   * @memberof PartialDiscordIntegrationResponse
   */
  account?: DiscordIntegrationResponseAccount;
  /**
   *
   * @type {any}
   * @memberof PartialDiscordIntegrationResponse
   */
  application_id: any;
}
