/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { DiscordIntegrationResponseAccount } from "./discord-integration-response-account";
// May contain unused imports in some cases
// @ts-ignore
import { IntegrationTypes } from "./integration-types";

/**
 *
 * @export
 * @interface PartialExternalConnectionIntegrationResponse
 */
export interface PartialExternalConnectionIntegrationResponse {
    /**
     *
     * @type {any}
     * @memberof PartialExternalConnectionIntegrationResponse
     */
    id: any;
    /**
     *
     * @type {IntegrationTypes}
     * @memberof PartialExternalConnectionIntegrationResponse
     */
    type: IntegrationTypes;
    /**
     *
     * @type {any}
     * @memberof PartialExternalConnectionIntegrationResponse
     */
    name?: any;
    /**
     *
     * @type {DiscordIntegrationResponseAccount}
     * @memberof PartialExternalConnectionIntegrationResponse
     */
    account?: DiscordIntegrationResponseAccount;
}
