/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PruneGuildRequest
 */
export interface PruneGuildRequest {
    /**
     * 
     * @type {number}
     * @memberof PruneGuildRequest
     */
    'days'?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof PruneGuildRequest
     */
    'compute_prune_count'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof PruneGuildRequest
     */
    'include_roles'?: string | null;
}

