/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GuildMemberResponse } from "./guild-member-response";
// May contain unused imports in some cases
// @ts-ignore
import { GuildRoleResponse } from "./guild-role-response";
// May contain unused imports in some cases
// @ts-ignore
import { ListGuildChannels200ResponseInner } from "./list-guild-channels200-response-inner";
// May contain unused imports in some cases
// @ts-ignore
import { UserResponse } from "./user-response";

/**
 *
 * @export
 * @interface ResolvedObjectsResponse
 */
export interface ResolvedObjectsResponse {
    /**
     *
     * @type {{ [key: string]: UserResponse; }}
     * @memberof ResolvedObjectsResponse
     */
    users: { [key: string]: UserResponse };
    /**
     *
     * @type {{ [key: string]: GuildMemberResponse; }}
     * @memberof ResolvedObjectsResponse
     */
    members: { [key: string]: GuildMemberResponse };
    /**
     *
     * @type {{ [key: string]: ListGuildChannels200ResponseInner; }}
     * @memberof ResolvedObjectsResponse
     */
    channels: { [key: string]: ListGuildChannels200ResponseInner };
    /**
     *
     * @type {{ [key: string]: GuildRoleResponse; }}
     * @memberof ResolvedObjectsResponse
     */
    roles: { [key: string]: GuildRoleResponse };
}
