/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { RichEmbedAuthor } from './rich-embed-author';
// May contain unused imports in some cases
// @ts-ignore
import { RichEmbedFooter } from './rich-embed-footer';
// May contain unused imports in some cases
// @ts-ignore
import { RichEmbedImage } from './rich-embed-image';
// May contain unused imports in some cases
// @ts-ignore
import { RichEmbedProvider } from './rich-embed-provider';
// May contain unused imports in some cases
// @ts-ignore
import { RichEmbedThumbnail } from './rich-embed-thumbnail';
// May contain unused imports in some cases
// @ts-ignore
import { RichEmbedVideo } from './rich-embed-video';

/**
 * 
 * @export
 * @interface RichEmbed
 */
export interface RichEmbed {
    /**
     * 
     * @type {any}
     * @memberof RichEmbed
     */
    'type'?: any;
    /**
     * 
     * @type {any}
     * @memberof RichEmbed
     */
    'url'?: any;
    /**
     * 
     * @type {any}
     * @memberof RichEmbed
     */
    'title'?: any;
    /**
     * 
     * @type {any}
     * @memberof RichEmbed
     */
    'color'?: any;
    /**
     * 
     * @type {any}
     * @memberof RichEmbed
     */
    'timestamp'?: any;
    /**
     * 
     * @type {any}
     * @memberof RichEmbed
     */
    'description'?: any;
    /**
     * 
     * @type {RichEmbedAuthor}
     * @memberof RichEmbed
     */
    'author'?: RichEmbedAuthor;
    /**
     * 
     * @type {RichEmbedImage}
     * @memberof RichEmbed
     */
    'image'?: RichEmbedImage;
    /**
     * 
     * @type {RichEmbedThumbnail}
     * @memberof RichEmbed
     */
    'thumbnail'?: RichEmbedThumbnail;
    /**
     * 
     * @type {RichEmbedFooter}
     * @memberof RichEmbed
     */
    'footer'?: RichEmbedFooter;
    /**
     * 
     * @type {any}
     * @memberof RichEmbed
     */
    'fields'?: any;
    /**
     * 
     * @type {RichEmbedProvider}
     * @memberof RichEmbed
     */
    'provider'?: RichEmbedProvider;
    /**
     * 
     * @type {RichEmbedVideo}
     * @memberof RichEmbed
     */
    'video'?: RichEmbedVideo;
}

