/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseApplicationId } from './basic-message-response-application-id';
// May contain unused imports in some cases
// @ts-ignore
import { ChannelFollowerWebhookResponseUser } from './channel-follower-webhook-response-user';
// May contain unused imports in some cases
// @ts-ignore
import { ExternalScheduledEventResponseUserRsvp } from './external-scheduled-event-response-user-rsvp';
// May contain unused imports in some cases
// @ts-ignore
import { GuildScheduledEventEntityTypes } from './guild-scheduled-event-entity-types';
// May contain unused imports in some cases
// @ts-ignore
import { GuildScheduledEventPrivacyLevels } from './guild-scheduled-event-privacy-levels';
// May contain unused imports in some cases
// @ts-ignore
import { GuildScheduledEventStatuses } from './guild-scheduled-event-statuses';

/**
 * 
 * @export
 * @interface ScheduledEventResponse
 */
export interface ScheduledEventResponse {
    /**
     * 
     * @type {any}
     * @memberof ScheduledEventResponse
     */
    'id': any;
    /**
     * 
     * @type {any}
     * @memberof ScheduledEventResponse
     */
    'guild_id': any;
    /**
     * 
     * @type {any}
     * @memberof ScheduledEventResponse
     */
    'name': any;
    /**
     * 
     * @type {any}
     * @memberof ScheduledEventResponse
     */
    'description'?: any;
    /**
     * 
     * @type {BasicMessageResponseApplicationId}
     * @memberof ScheduledEventResponse
     */
    'channel_id'?: BasicMessageResponseApplicationId;
    /**
     * 
     * @type {BasicMessageResponseApplicationId}
     * @memberof ScheduledEventResponse
     */
    'creator_id'?: BasicMessageResponseApplicationId;
    /**
     * 
     * @type {ChannelFollowerWebhookResponseUser}
     * @memberof ScheduledEventResponse
     */
    'creator'?: ChannelFollowerWebhookResponseUser;
    /**
     * 
     * @type {any}
     * @memberof ScheduledEventResponse
     */
    'image'?: any;
    /**
     * 
     * @type {any}
     * @memberof ScheduledEventResponse
     */
    'scheduled_start_time': any;
    /**
     * 
     * @type {any}
     * @memberof ScheduledEventResponse
     */
    'scheduled_end_time'?: any;
    /**
     * 
     * @type {GuildScheduledEventStatuses}
     * @memberof ScheduledEventResponse
     */
    'status': GuildScheduledEventStatuses;
    /**
     * 
     * @type {GuildScheduledEventEntityTypes}
     * @memberof ScheduledEventResponse
     */
    'entity_type': GuildScheduledEventEntityTypes;
    /**
     * 
     * @type {BasicMessageResponseApplicationId}
     * @memberof ScheduledEventResponse
     */
    'entity_id'?: BasicMessageResponseApplicationId;
    /**
     * 
     * @type {any}
     * @memberof ScheduledEventResponse
     */
    'user_count'?: any;
    /**
     * 
     * @type {GuildScheduledEventPrivacyLevels}
     * @memberof ScheduledEventResponse
     */
    'privacy_level': GuildScheduledEventPrivacyLevels;
    /**
     * 
     * @type {ExternalScheduledEventResponseUserRsvp}
     * @memberof ScheduledEventResponse
     */
    'user_rsvp'?: ExternalScheduledEventResponseUserRsvp;
}

