/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ButtonEmoji } from "./button-emoji";

/**
 *
 * @export
 * @interface SelectOption
 */
export interface SelectOption {
  /**
   *
   * @type {any}
   * @memberof SelectOption
   */
  label: any;
  /**
   *
   * @type {any}
   * @memberof SelectOption
   */
  value: any;
  /**
   *
   * @type {any}
   * @memberof SelectOption
   */
  description?: any;
  /**
   *
   * @type {ButtonEmoji}
   * @memberof SelectOption
   */
  emoji?: ButtonEmoji;
  /**
   *
   * @type {any}
   * @memberof SelectOption
   */
  default?: any;
}
