/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { MessageComponentButtonResponseEmoji } from "./message-component-button-response-emoji";

/**
 *
 * @export
 * @interface SelectOptionResponse
 */
export interface SelectOptionResponse {
    /**
     *
     * @type {any}
     * @memberof SelectOptionResponse
     */
    label: any;
    /**
     *
     * @type {any}
     * @memberof SelectOptionResponse
     */
    value: any;
    /**
     *
     * @type {any}
     * @memberof SelectOptionResponse
     */
    description?: any;
    /**
     *
     * @type {MessageComponentButtonResponseEmoji}
     * @memberof SelectOptionResponse
     */
    emoji?: MessageComponentButtonResponseEmoji;
    /**
     *
     * @type {any}
     * @memberof SelectOptionResponse
     */
    default?: any;
}
