/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseApplicationId } from "./basic-message-response-application-id";
// May contain unused imports in some cases
// @ts-ignore
import { StageInstancesPrivacyLevels } from "./stage-instances-privacy-levels";

/**
 *
 * @export
 * @interface StageInstanceResponse
 */
export interface StageInstanceResponse {
    /**
     *
     * @type {any}
     * @memberof StageInstanceResponse
     */
    guild_id: any;
    /**
     *
     * @type {any}
     * @memberof StageInstanceResponse
     */
    channel_id: any;
    /**
     *
     * @type {any}
     * @memberof StageInstanceResponse
     */
    topic: any;
    /**
     *
     * @type {StageInstancesPrivacyLevels}
     * @memberof StageInstanceResponse
     */
    privacy_level: StageInstancesPrivacyLevels;
    /**
     *
     * @type {any}
     * @memberof StageInstanceResponse
     */
    id: any;
    /**
     *
     * @type {any}
     * @memberof StageInstanceResponse
     */
    discoverable_disabled?: any;
    /**
     *
     * @type {BasicMessageResponseApplicationId}
     * @memberof StageInstanceResponse
     */
    guild_scheduled_event_id?: BasicMessageResponseApplicationId;
}
