/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseApplicationId } from './basic-message-response-application-id';
// May contain unused imports in some cases
// @ts-ignore
import { ExternalScheduledEventPatchRequestPartialStatus } from './external-scheduled-event-patch-request-partial-status';
// May contain unused imports in some cases
// @ts-ignore
import { GuildScheduledEventPrivacyLevels } from './guild-scheduled-event-privacy-levels';
// May contain unused imports in some cases
// @ts-ignore
import { StageScheduledEventCreateRequestEntityMetadata } from './stage-scheduled-event-create-request-entity-metadata';
// May contain unused imports in some cases
// @ts-ignore
import { StageScheduledEventPatchRequestPartialEntityType } from './stage-scheduled-event-patch-request-partial-entity-type';

/**
 * 
 * @export
 * @interface StageScheduledEventPatchRequestPartial
 */
export interface StageScheduledEventPatchRequestPartial {
    /**
     * 
     * @type {ExternalScheduledEventPatchRequestPartialStatus}
     * @memberof StageScheduledEventPatchRequestPartial
     */
    'status'?: ExternalScheduledEventPatchRequestPartialStatus;
    /**
     * 
     * @type {any}
     * @memberof StageScheduledEventPatchRequestPartial
     */
    'name'?: any;
    /**
     * 
     * @type {any}
     * @memberof StageScheduledEventPatchRequestPartial
     */
    'description'?: any;
    /**
     * 
     * @type {any}
     * @memberof StageScheduledEventPatchRequestPartial
     */
    'image'?: any;
    /**
     * 
     * @type {any}
     * @memberof StageScheduledEventPatchRequestPartial
     */
    'scheduled_start_time'?: any;
    /**
     * 
     * @type {any}
     * @memberof StageScheduledEventPatchRequestPartial
     */
    'scheduled_end_time'?: any;
    /**
     * 
     * @type {StageScheduledEventPatchRequestPartialEntityType}
     * @memberof StageScheduledEventPatchRequestPartial
     */
    'entity_type'?: StageScheduledEventPatchRequestPartialEntityType;
    /**
     * 
     * @type {GuildScheduledEventPrivacyLevels}
     * @memberof StageScheduledEventPatchRequestPartial
     */
    'privacy_level'?: GuildScheduledEventPrivacyLevels;
    /**
     * 
     * @type {BasicMessageResponseApplicationId}
     * @memberof StageScheduledEventPatchRequestPartial
     */
    'channel_id'?: BasicMessageResponseApplicationId;
    /**
     * 
     * @type {StageScheduledEventCreateRequestEntityMetadata}
     * @memberof StageScheduledEventPatchRequestPartial
     */
    'entity_metadata'?: StageScheduledEventCreateRequestEntityMetadata;
}

