/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseApplicationId } from "./basic-message-response-application-id";
// May contain unused imports in some cases
// @ts-ignore
import { GuildScheduledEventEntityTypes } from "./guild-scheduled-event-entity-types";
// May contain unused imports in some cases
// @ts-ignore
import { GuildScheduledEventPrivacyLevels } from "./guild-scheduled-event-privacy-levels";
// May contain unused imports in some cases
// @ts-ignore
import { StageScheduledEventCreateRequestEntityMetadata } from "./stage-scheduled-event-create-request-entity-metadata";

/**
 *
 * @export
 * @interface StageScheduledEventCreateRequest
 */
export interface StageScheduledEventCreateRequest {
    /**
     *
     * @type {any}
     * @memberof StageScheduledEventCreateRequest
     */
    name: any;
    /**
     *
     * @type {any}
     * @memberof StageScheduledEventCreateRequest
     */
    description?: any;
    /**
     *
     * @type {any}
     * @memberof StageScheduledEventCreateRequest
     */
    image?: any;
    /**
     *
     * @type {any}
     * @memberof StageScheduledEventCreateRequest
     */
    scheduled_start_time: any;
    /**
     *
     * @type {any}
     * @memberof StageScheduledEventCreateRequest
     */
    scheduled_end_time?: any;
    /**
     *
     * @type {GuildScheduledEventPrivacyLevels}
     * @memberof StageScheduledEventCreateRequest
     */
    privacy_level: GuildScheduledEventPrivacyLevels;
    /**
     *
     * @type {GuildScheduledEventEntityTypes}
     * @memberof StageScheduledEventCreateRequest
     */
    entity_type: GuildScheduledEventEntityTypes;
    /**
     *
     * @type {BasicMessageResponseApplicationId}
     * @memberof StageScheduledEventCreateRequest
     */
    channel_id?: BasicMessageResponseApplicationId;
    /**
     *
     * @type {StageScheduledEventCreateRequestEntityMetadata}
     * @memberof StageScheduledEventCreateRequest
     */
    entity_metadata?: StageScheduledEventCreateRequestEntityMetadata;
}
