/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TeamResponse
 */
export interface TeamResponse {
    /**
     * 
     * @type {any}
     * @memberof TeamResponse
     */
    'id': any;
    /**
     * 
     * @type {any}
     * @memberof TeamResponse
     */
    'icon'?: any;
    /**
     * 
     * @type {any}
     * @memberof TeamResponse
     */
    'name': any;
    /**
     * 
     * @type {any}
     * @memberof TeamResponse
     */
    'owner_user_id': any;
    /**
     * 
     * @type {any}
     * @memberof TeamResponse
     */
    'members': any;
}

