/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { TeamMembershipStates } from "./team-membership-states";
// May contain unused imports in some cases
// @ts-ignore
import { UserResponse } from "./user-response";

/**
 *
 * @export
 * @interface TeamMemberResponse
 */
export interface TeamMemberResponse {
    /**
     *
     * @type {UserResponse}
     * @memberof TeamMemberResponse
     */
    user: UserResponse;
    /**
     *
     * @type {any}
     * @memberof TeamMemberResponse
     */
    team_id: any;
    /**
     *
     * @type {TeamMembershipStates}
     * @memberof TeamMemberResponse
     */
    membership_state: TeamMembershipStates;
}
