/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ChannelTypes } from "./channel-types";
// May contain unused imports in some cases
// @ts-ignore
import { CreateGuildChannelRequestVideoQualityMode } from "./create-guild-channel-request-video-quality-mode";
// May contain unused imports in some cases
// @ts-ignore
import { CreatedThreadResponseMember } from "./created-thread-response-member";
// May contain unused imports in some cases
// @ts-ignore
import { CreatedThreadResponseThreadMetadata } from "./created-thread-response-thread-metadata";
// May contain unused imports in some cases
// @ts-ignore
import { UpdateSelfVoiceStateRequestChannelId } from "./update-self-voice-state-request-channel-id";

/**
 *
 * @export
 * @interface ThreadResponse
 */
export interface ThreadResponse {
  /**
   *
   * @type {any}
   * @memberof ThreadResponse
   */
  id: any;
  /**
   *
   * @type {ChannelTypes}
   * @memberof ThreadResponse
   */
  type: ChannelTypes;
  /**
   *
   * @type {UpdateSelfVoiceStateRequestChannelId}
   * @memberof ThreadResponse
   */
  last_message_id?: UpdateSelfVoiceStateRequestChannelId | null;
  /**
   *
   * @type {number}
   * @memberof ThreadResponse
   */
  flags: number;
  /**
   *
   * @type {string}
   * @memberof ThreadResponse
   */
  last_pin_timestamp?: string | null;
  /**
   *
   * @type {any}
   * @memberof ThreadResponse
   */
  guild_id: any;
  /**
   *
   * @type {string}
   * @memberof ThreadResponse
   */
  name: string | null;
  /**
   *
   * @type {UpdateSelfVoiceStateRequestChannelId}
   * @memberof ThreadResponse
   */
  parent_id?: UpdateSelfVoiceStateRequestChannelId | null;
  /**
   *
   * @type {number}
   * @memberof ThreadResponse
   */
  rate_limit_per_user?: number | null;
  /**
   *
   * @type {number}
   * @memberof ThreadResponse
   */
  bitrate?: number | null;
  /**
   *
   * @type {number}
   * @memberof ThreadResponse
   */
  user_limit?: number | null;
  /**
   *
   * @type {string}
   * @memberof ThreadResponse
   */
  rtc_region?: string | null;
  /**
   *
   * @type {CreateGuildChannelRequestVideoQualityMode}
   * @memberof ThreadResponse
   */
  video_quality_mode?: CreateGuildChannelRequestVideoQualityMode;
  /**
   *
   * @type {string}
   * @memberof ThreadResponse
   */
  permissions?: string | null;
  /**
   *
   * @type {any}
   * @memberof ThreadResponse
   */
  owner_id: any;
  /**
   *
   * @type {CreatedThreadResponseThreadMetadata}
   * @memberof ThreadResponse
   */
  thread_metadata?: CreatedThreadResponseThreadMetadata;
  /**
   *
   * @type {number}
   * @memberof ThreadResponse
   */
  message_count: number;
  /**
   *
   * @type {number}
   * @memberof ThreadResponse
   */
  member_count: number;
  /**
   *
   * @type {number}
   * @memberof ThreadResponse
   */
  total_message_sent: number;
  /**
   *
   * @type {any}
   * @memberof ThreadResponse
   */
  applied_tags?: any;
  /**
   *
   * @type {CreatedThreadResponseMember}
   * @memberof ThreadResponse
   */
  member?: CreatedThreadResponseMember;
}
