/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ScheduledEventUserResponseMember } from "./scheduled-event-user-response-member";

/**
 *
 * @export
 * @interface ThreadMemberResponse
 */
export interface ThreadMemberResponse {
  /**
   *
   * @type {any}
   * @memberof ThreadMemberResponse
   */
  id: any;
  /**
   *
   * @type {any}
   * @memberof ThreadMemberResponse
   */
  user_id: any;
  /**
   *
   * @type {any}
   * @memberof ThreadMemberResponse
   */
  join_timestamp: any;
  /**
   *
   * @type {any}
   * @memberof ThreadMemberResponse
   */
  flags: any;
  /**
   *
   * @type {ScheduledEventUserResponseMember}
   * @memberof ThreadMemberResponse
   */
  member?: ScheduledEventUserResponseMember;
}
