/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { UpdateGuildOnboardingRequestMode } from "./update-guild-onboarding-request-mode";

/**
 *
 * @export
 * @interface UpdateGuildOnboardingRequest
 */
export interface UpdateGuildOnboardingRequest {
  /**
   *
   * @type {any}
   * @memberof UpdateGuildOnboardingRequest
   */
  prompts?: any;
  /**
   *
   * @type {any}
   * @memberof UpdateGuildOnboardingRequest
   */
  enabled?: any;
  /**
   *
   * @type {any}
   * @memberof UpdateGuildOnboardingRequest
   */
  default_channel_ids?: any;
  /**
   *
   * @type {UpdateGuildOnboardingRequestMode}
   * @memberof UpdateGuildOnboardingRequest
   */
  mode?: UpdateGuildOnboardingRequestMode;
}
