/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseApplicationId } from "./basic-message-response-application-id";
// May contain unused imports in some cases
// @ts-ignore
import { CreateForumThreadRequestAutoArchiveDuration } from "./create-forum-thread-request-auto-archive-duration";
// May contain unused imports in some cases
// @ts-ignore
import { CreateGuildChannelRequestDefaultForumLayout } from "./create-guild-channel-request-default-forum-layout";
// May contain unused imports in some cases
// @ts-ignore
import { CreateGuildChannelRequestDefaultReactionEmoji } from "./create-guild-channel-request-default-reaction-emoji";
// May contain unused imports in some cases
// @ts-ignore
import { CreateGuildChannelRequestDefaultSortOrder } from "./create-guild-channel-request-default-sort-order";
// May contain unused imports in some cases
// @ts-ignore
import { CreateGuildChannelRequestType } from "./create-guild-channel-request-type";
// May contain unused imports in some cases
// @ts-ignore
import { CreateGuildChannelRequestVideoQualityMode } from "./create-guild-channel-request-video-quality-mode";
// May contain unused imports in some cases
// @ts-ignore
import { PrivateChannelRequestPartial } from "./private-channel-request-partial";
// May contain unused imports in some cases
// @ts-ignore
import { UpdateGuildChannelRequestPartial } from "./update-guild-channel-request-partial";
// May contain unused imports in some cases
// @ts-ignore
import { UpdateThreadRequestPartial } from "./update-thread-request-partial";

/**
 *
 * @export
 * @interface UpdateChannelRequest
 */
export interface UpdateChannelRequest {
    /**
     *
     * @type {any}
     * @memberof UpdateChannelRequest
     */
    name?: any;
    /**
     *
     * @type {any}
     * @memberof UpdateChannelRequest
     */
    icon?: any;
    /**
     *
     * @type {CreateGuildChannelRequestType}
     * @memberof UpdateChannelRequest
     */
    type?: CreateGuildChannelRequestType;
    /**
     *
     * @type {any}
     * @memberof UpdateChannelRequest
     */
    position?: any;
    /**
     *
     * @type {any}
     * @memberof UpdateChannelRequest
     */
    topic?: any;
    /**
     *
     * @type {any}
     * @memberof UpdateChannelRequest
     */
    bitrate?: any;
    /**
     *
     * @type {any}
     * @memberof UpdateChannelRequest
     */
    user_limit?: any;
    /**
     *
     * @type {any}
     * @memberof UpdateChannelRequest
     */
    nsfw?: any;
    /**
     *
     * @type {any}
     * @memberof UpdateChannelRequest
     */
    rate_limit_per_user?: any;
    /**
     *
     * @type {BasicMessageResponseApplicationId}
     * @memberof UpdateChannelRequest
     */
    parent_id?: BasicMessageResponseApplicationId;
    /**
     *
     * @type {any}
     * @memberof UpdateChannelRequest
     */
    permission_overwrites?: any;
    /**
     *
     * @type {any}
     * @memberof UpdateChannelRequest
     */
    rtc_region?: any;
    /**
     *
     * @type {CreateGuildChannelRequestVideoQualityMode}
     * @memberof UpdateChannelRequest
     */
    video_quality_mode?: CreateGuildChannelRequestVideoQualityMode;
    /**
     *
     * @type {CreateForumThreadRequestAutoArchiveDuration}
     * @memberof UpdateChannelRequest
     */
    default_auto_archive_duration?: CreateForumThreadRequestAutoArchiveDuration;
    /**
     *
     * @type {CreateGuildChannelRequestDefaultReactionEmoji}
     * @memberof UpdateChannelRequest
     */
    default_reaction_emoji?: CreateGuildChannelRequestDefaultReactionEmoji;
    /**
     *
     * @type {any}
     * @memberof UpdateChannelRequest
     */
    default_thread_rate_limit_per_user?: any;
    /**
     *
     * @type {CreateGuildChannelRequestDefaultSortOrder}
     * @memberof UpdateChannelRequest
     */
    default_sort_order?: CreateGuildChannelRequestDefaultSortOrder;
    /**
     *
     * @type {CreateGuildChannelRequestDefaultForumLayout}
     * @memberof UpdateChannelRequest
     */
    default_forum_layout?: CreateGuildChannelRequestDefaultForumLayout;
    /**
     *
     * @type {any}
     * @memberof UpdateChannelRequest
     */
    flags?: any;
    /**
     *
     * @type {any}
     * @memberof UpdateChannelRequest
     */
    available_tags?: any;
    /**
     *
     * @type {any}
     * @memberof UpdateChannelRequest
     */
    archived?: any;
    /**
     *
     * @type {any}
     * @memberof UpdateChannelRequest
     */
    locked?: any;
    /**
     *
     * @type {any}
     * @memberof UpdateChannelRequest
     */
    invitable?: any;
    /**
     *
     * @type {CreateForumThreadRequestAutoArchiveDuration}
     * @memberof UpdateChannelRequest
     */
    auto_archive_duration?: CreateForumThreadRequestAutoArchiveDuration;
    /**
     *
     * @type {any}
     * @memberof UpdateChannelRequest
     */
    applied_tags?: any;
}
