/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateGuildRoleRequest
 */
export interface UpdateGuildRoleRequest {
    /**
     *
     * @type {string}
     * @memberof UpdateGuildRoleRequest
     */
    name?: string | null;
    /**
     *
     * @type {number}
     * @memberof UpdateGuildRoleRequest
     */
    permissions?: number | null;
    /**
     *
     * @type {number}
     * @memberof UpdateGuildRoleRequest
     */
    color?: number | null;
    /**
     *
     * @type {boolean}
     * @memberof UpdateGuildRoleRequest
     */
    hoist?: boolean | null;
    /**
     *
     * @type {boolean}
     * @memberof UpdateGuildRoleRequest
     */
    mentionable?: boolean | null;
    /**
     *
     * @type {string}
     * @memberof UpdateGuildRoleRequest
     */
    icon?: string | null;
    /**
     *
     * @type {string}
     * @memberof UpdateGuildRoleRequest
     */
    unicode_emoji?: string | null;
}
