/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { CreateForumThreadRequestAutoArchiveDuration } from "./create-forum-thread-request-auto-archive-duration";
// May contain unused imports in some cases
// @ts-ignore
import { CreateGuildChannelRequestVideoQualityMode } from "./create-guild-channel-request-video-quality-mode";

/**
 *
 * @export
 * @interface UpdateThreadRequestPartial
 */
export interface UpdateThreadRequestPartial {
  /**
   *
   * @type {any}
   * @memberof UpdateThreadRequestPartial
   */
  name?: any;
  /**
   *
   * @type {any}
   * @memberof UpdateThreadRequestPartial
   */
  archived?: any;
  /**
   *
   * @type {any}
   * @memberof UpdateThreadRequestPartial
   */
  locked?: any;
  /**
   *
   * @type {any}
   * @memberof UpdateThreadRequestPartial
   */
  invitable?: any;
  /**
   *
   * @type {CreateForumThreadRequestAutoArchiveDuration}
   * @memberof UpdateThreadRequestPartial
   */
  auto_archive_duration?: CreateForumThreadRequestAutoArchiveDuration;
  /**
   *
   * @type {any}
   * @memberof UpdateThreadRequestPartial
   */
  rate_limit_per_user?: any;
  /**
   *
   * @type {any}
   * @memberof UpdateThreadRequestPartial
   */
  flags?: any;
  /**
   *
   * @type {any}
   * @memberof UpdateThreadRequestPartial
   */
  applied_tags?: any;
  /**
   *
   * @type {any}
   * @memberof UpdateThreadRequestPartial
   */
  bitrate?: any;
  /**
   *
   * @type {any}
   * @memberof UpdateThreadRequestPartial
   */
  user_limit?: any;
  /**
   *
   * @type {any}
   * @memberof UpdateThreadRequestPartial
   */
  rtc_region?: any;
  /**
   *
   * @type {CreateGuildChannelRequestVideoQualityMode}
   * @memberof UpdateThreadRequestPartial
   */
  video_quality_mode?: CreateGuildChannelRequestVideoQualityMode;
}
