/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UpdateSelfVoiceStateRequestChannelId } from './update-self-voice-state-request-channel-id';

/**
 * 
 * @export
 * @interface UpdateGuildMemberRequest
 */
export interface UpdateGuildMemberRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateGuildMemberRequest
     */
    'nick'?: string | null;
    /**
     * 
     * @type {Array<any>}
     * @memberof UpdateGuildMemberRequest
     */
    'roles'?: Array<any>;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateGuildMemberRequest
     */
    'mute'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateGuildMemberRequest
     */
    'deaf'?: boolean | null;
    /**
     * 
     * @type {UpdateSelfVoiceStateRequestChannelId}
     * @memberof UpdateGuildMemberRequest
     */
    'channel_id'?: UpdateSelfVoiceStateRequestChannelId | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateGuildMemberRequest
     */
    'communication_disabled_until'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateGuildMemberRequest
     */
    'flags'?: number | null;
}

