/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { UpdateOnboardingPromptRequestType } from "./update-onboarding-prompt-request-type";

/**
 *
 * @export
 * @interface UpdateOnboardingPromptRequest
 */
export interface UpdateOnboardingPromptRequest {
  /**
   *
   * @type {any}
   * @memberof UpdateOnboardingPromptRequest
   */
  title: any;
  /**
   *
   * @type {any}
   * @memberof UpdateOnboardingPromptRequest
   */
  options: any;
  /**
   *
   * @type {any}
   * @memberof UpdateOnboardingPromptRequest
   */
  single_select?: any;
  /**
   *
   * @type {any}
   * @memberof UpdateOnboardingPromptRequest
   */
  required?: any;
  /**
   *
   * @type {any}
   * @memberof UpdateOnboardingPromptRequest
   */
  in_onboarding?: any;
  /**
   *
   * @type {UpdateOnboardingPromptRequestType}
   * @memberof UpdateOnboardingPromptRequest
   */
  type?: UpdateOnboardingPromptRequestType;
  /**
   *
   * @type {any}
   * @memberof UpdateOnboardingPromptRequest
   */
  id: any;
}
