/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface WebhookSlackEmbed
 */
export interface WebhookSlackEmbed {
  /**
   *
   * @type {any}
   * @memberof WebhookSlackEmbed
   */
  title?: any;
  /**
   *
   * @type {any}
   * @memberof WebhookSlackEmbed
   */
  title_link?: any;
  /**
   *
   * @type {any}
   * @memberof WebhookSlackEmbed
   */
  text?: any;
  /**
   *
   * @type {any}
   * @memberof WebhookSlackEmbed
   */
  color?: any;
  /**
   *
   * @type {any}
   * @memberof WebhookSlackEmbed
   */
  ts?: any;
  /**
   *
   * @type {any}
   * @memberof WebhookSlackEmbed
   */
  pretext?: any;
  /**
   *
   * @type {any}
   * @memberof WebhookSlackEmbed
   */
  footer?: any;
  /**
   *
   * @type {any}
   * @memberof WebhookSlackEmbed
   */
  footer_icon?: any;
  /**
   *
   * @type {any}
   * @memberof WebhookSlackEmbed
   */
  author_name?: any;
  /**
   *
   * @type {any}
   * @memberof WebhookSlackEmbed
   */
  author_link?: any;
  /**
   *
   * @type {any}
   * @memberof WebhookSlackEmbed
   */
  author_icon?: any;
  /**
   *
   * @type {any}
   * @memberof WebhookSlackEmbed
   */
  image_url?: any;
  /**
   *
   * @type {any}
   * @memberof WebhookSlackEmbed
   */
  thumb_url?: any;
  /**
   *
   * @type {any}
   * @memberof WebhookSlackEmbed
   */
  fields?: any;
}
