/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface WidgetResponse
 */
export interface WidgetResponse {
    /**
     *
     * @type {any}
     * @memberof WidgetResponse
     */
    id: any;
    /**
     *
     * @type {any}
     * @memberof WidgetResponse
     */
    name: any;
    /**
     *
     * @type {any}
     * @memberof WidgetResponse
     */
    instant_invite?: any;
    /**
     *
     * @type {any}
     * @memberof WidgetResponse
     */
    channels: any;
    /**
     *
     * @type {any}
     * @memberof WidgetResponse
     */
    members: any;
    /**
     *
     * @type {any}
     * @memberof WidgetResponse
     */
    presence_count: any;
}
