/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BasicMessageResponseApplicationId } from './basic-message-response-application-id';
// May contain unused imports in some cases
// @ts-ignore
import { WidgetMemberActivity } from './widget-member-activity';
// May contain unused imports in some cases
// @ts-ignore
import { WidgetUserDiscriminator } from './widget-user-discriminator';

/**
 * 
 * @export
 * @interface WidgetMember
 */
export interface WidgetMember {
    /**
     * 
     * @type {any}
     * @memberof WidgetMember
     */
    'id': any;
    /**
     * 
     * @type {any}
     * @memberof WidgetMember
     */
    'username': any;
    /**
     * 
     * @type {WidgetUserDiscriminator}
     * @memberof WidgetMember
     */
    'discriminator': WidgetUserDiscriminator;
    /**
     * 
     * @type {any}
     * @memberof WidgetMember
     */
    'avatar'?: any;
    /**
     * 
     * @type {any}
     * @memberof WidgetMember
     */
    'status': any;
    /**
     * 
     * @type {any}
     * @memberof WidgetMember
     */
    'avatar_url': any;
    /**
     * 
     * @type {WidgetMemberActivity}
     * @memberof WidgetMember
     */
    'activity'?: WidgetMemberActivity;
    /**
     * 
     * @type {any}
     * @memberof WidgetMember
     */
    'deaf'?: any;
    /**
     * 
     * @type {any}
     * @memberof WidgetMember
     */
    'mute'?: any;
    /**
     * 
     * @type {any}
     * @memberof WidgetMember
     */
    'self_deaf'?: any;
    /**
     * 
     * @type {any}
     * @memberof WidgetMember
     */
    'self_mute'?: any;
    /**
     * 
     * @type {any}
     * @memberof WidgetMember
     */
    'suppress'?: any;
    /**
     * 
     * @type {BasicMessageResponseApplicationId}
     * @memberof WidgetMember
     */
    'channel_id'?: BasicMessageResponseApplicationId;
}

